### ISSUE TITLE
Spring contracts does not work when input and output queue name is same

### ISSUE THREAD

**Issue by yogi1817** [spring-cloud/spring-cloud-contract#1486] opened 2020-08-29 14:20 UTC
Hello,

In this case my input and output stream both pints to the same queue. When i create a contract and run it errors out.
**cloud.stream.bindings.output.destination=spring-boot-exchange
cloud.stream.bindings.inout.destination=spring-boot-exchange**

The below error happens as the stream code tries to read the default Input queue.
org.springframework.cloud.contract.verifier.messaging.stream.StreamMessageCollectorMessageReceiver
MessageChannel messageChannel = this.context.getBean(
					this.resolver.resolvedDestination(destination, DefaultChannels.INPUT),
					MessageChannel.class);

java.lang.IllegalArgumentException: Channel [bean 'input'] was not bound by class org.springframework.cloud.stream.test.binder.TestSupportBinder
	at org.springframework.util.Assert.notNull(Assert.java:198) ~[spring-core-5.2.2.RELEASE.jar:5.2.2.RELEASE]
	at org.springframework.cloud.stream.test.binder.TestSupportBinder$MessageCollectorImpl.forChannel(TestSupportBinder.java:140) ~[spring-cloud-stream-test-support-3.0.4.RELEASE.jar:3.0.4.RELEASE]
	at org.springframework.cloud.contract.verifier.messaging.stream.StreamMessageCollectorMessageReceiver.receive(StreamMessageCollectorMessageReceiver.java:54) ~[spring-cloud-contract-verifier-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.contract.verifier.messaging.stream.StreamMessageCollectorMessageReceiver.receive(StreamMessageCollectorMessageReceiver.java:72) ~[spring-cloud-contract-verifier-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.contract.verifier.messaging.stream.StreamMessageCollectorMessageReceiver.receive(StreamMessageCollectorMessageReceiver.java:30) ~[spring-cloud-contract-verifier-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.contract.verifier.messaging.stream.StreamStubMessages.receive(StreamStubMessages.java:59) ~[spring-cloud-contract-verifier-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.contract.verifier.messaging.stream.StreamStubMessages.receive(StreamStubMessages.java:30) ~[spring-cloud-contract-verifier-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.contract.verifier.messaging.internal.ContractVerifierMessaging.receive(ContractVerifierMessaging.java:44) ~[spring-cloud-contract-verifier-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at findMySalon.FindMySalonTest.validate_sendAMessage(FindMySalonTest.java:72) ~[test/:?]

**Attached is my github repo branch spring-contracts
https://github.com/yogi1817/findMySalon/tree/spring-contracts**

**Comment by marcingrzejszczak** [comment] 2020-08-31 12:34
If I click at the repo I get 404

**Comment by yogi1817** [comment] 2020-08-31 12:56
Can you try now, it was a private repo i made it public.

**Comment by marcingrzejszczak** [comment] 2020-12-08 10:10
Duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/1439

**Closed by marcingrzejszczak** 2020-12-08 10:10 UTC
Labels: bug
