### ISSUE TITLE
Running wiremock mocks in multiple integration test overlaps responses.

### ISSUE THREAD

**Issue by Marek00Malik** [spring-cloud/spring-cloud-contract#715] opened 2018-08-27 12:01 UTC
Question

Hello, 
I'm experiencing the following issue. 
Each time I fire my integration tests with wiremocks running in gradle, I'm getting a number of different responses. The bad responses come from other stubs that are used in different tests. 
My configuration as of now requires that I ran each test using mocks with a different port for Wiremock 

> @AutoConfigureWireMock(port = xxxx)

This required that the setup needs to be splited, and we are not able to have some default configuration. 

My setup:
I ran each test with the following configuration:

> @ExtendWith(SpringExtension.class)
> @SpringBootTest(webEnvironment = WebEnvironment.MOCK)
> @AutoConfigureWireMock(port = xxxx)

Setting port = 0, does not prevent this issue.

**Comment by marcingrzejszczak** [comment] 2018-08-27 12:02
Which version of Spring Cloud Contract do you use?

**Comment by marcingrzejszczak** [comment] 2018-08-27 12:03
IMO this is a duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/706

**Comment by Marek00Malik** [comment] 2018-08-27 12:03
Wow, your quick :D, 

>   compile "com.github.tomakehurst:wiremock:2.18.0"
>   compile "org.springframework.cloud:spring-cloud-starter-contract-stub-runner:1.2.4.RELEASE"
>   compile "org.springframework.cloud:spring-cloud-contract-wiremock:1.2.4.RELEASE"

I;m also running JUnit 5.

**Comment by marcingrzejszczak** [comment] 2018-08-27 12:07
Yeah, that's a duplicate of #665. So you'll have to wait until we release  2.1.0 or use a different port or use `@DirtiesContext`.

**Closed by marcingrzejszczak** 2018-08-27 12:07 UTC
Labels: question

**Comment by Marek00Malik** [comment] 2018-08-27 12:18
DirtiesContex fix the problem. Thanks :)
