### ISSUE TITLE
NPE while triggering stub for amqp with non-transactional publisher-confirms mode if mockConnection: false

### ISSUE THREAD

**Issue by lde-avaleo** [spring-cloud/spring-cloud-contract#859] opened 2019-01-22 13:23 UTC
There is a problem with `SpringAmqpStubMessages#send()` method when using real rabbitmq connections (mockConnection: false). It is assuming that rabbitmq is configured with transactional mode while creating channel. However if publisher-confirms mode is used then following exception is thrown:
```
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - cannot switch from tx to confirm mode, class-id=85, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:516)
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:346)
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:178)
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:111)
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:670)
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48)
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:597)
	at java.lang.Thread.run(Thread.java:748)
```
due to above `SpringAmqpStubMessages#send()` method also throws exception
```
java.io.IOException: null
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:126)
	at com.rabbitmq.client.impl.AMQChannel.wrap(AMQChannel.java:122)
	at com.rabbitmq.client.impl.AMQChannel.exnWrappingRpc(AMQChannel.java:144)
	at com.rabbitmq.client.impl.ChannelN.confirmSelect(ChannelN.java:1552)
	at com.rabbitmq.client.impl.ChannelN.confirmSelect(ChannelN.java:52)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.doCreateBareChannel(CachingConnectionFactory.java:657)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:637)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getCachedChannelProxy(CachingConnectionFactory.java:607)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getChannel(CachingConnectionFactory.java:498)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$1600(CachingConnectionFactory.java:101)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createChannel(CachingConnectionFactory.java:1331)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:135)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:102)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.sendMessage(StubRunnerExecutor.java:257)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.triggerForDsls(StubRunnerExecutor.java:213)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.trigger(StubRunnerExecutor.java:198)
	at org.springframework.cloud.contract.stubrunner.StubRunner.trigger(StubRunner.java:160)
	at org.springframework.cloud.contract.stubrunner.BatchStubRunner.trigger(BatchStubRunner.java:135)
	at org.springframework.cloud.contract.stubrunner.StubTrigger$trigger.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
[...]
java.lang.RuntimeException: java.lang.NullPointerException

	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:138)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:102)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.sendMessage(StubRunnerExecutor.java:257)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.triggerForDsls(StubRunnerExecutor.java:213)
	at org.springframework.cloud.contract.stubrunner.StubRunnerExecutor.trigger(StubRunnerExecutor.java:198)
	at org.springframework.cloud.contract.stubrunner.StubRunner.trigger(StubRunner.java:160)
	at org.springframework.cloud.contract.stubrunner.BatchStubRunner.trigger(BatchStubRunner.java:135)
[...]
Caused by: java.lang.NullPointerException
	at org.springframework.amqp.rabbit.connection.PublisherCallbackChannelImpl.shutdownCompleted(PublisherCallbackChannelImpl.java:828)
	at org.springframework.amqp.rabbit.connection.PublisherCallbackChannelImpl.shutdownCompleted(PublisherCallbackChannelImpl.java:1107)
	at com.rabbitmq.client.impl.ShutdownNotifierComponent.addShutdownListener(ShutdownNotifierComponent.java:55)
	at org.springframework.amqp.rabbit.connection.PublisherCallbackChannelImpl.<init>(PublisherCallbackChannelImpl.java:128)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.doCreateBareChannel(CachingConnectionFactory.java:665)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:637)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getCachedChannelProxy(CachingConnectionFactory.java:607)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getChannel(CachingConnectionFactory.java:498)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$1600(CachingConnectionFactory.java:101)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createChannel(CachingConnectionFactory.java:1331)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:135)
	... 7 more
```

To reproduce this case we need to have running rabbitmq server and spring-boot app configured with property `spring.rabbitmq.publisher-confirms=true` and of course stub runner should be configured to not mock connection `stubrunner.amqp.mockConnection=false`

regards,
Lukasz

**Comment by OlgaMaciaszek** [comment] 2019-01-23 10:18
Hello @lde-avaleo it looks like a valid issue. Thanks for reporting it. Could you please provide an [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue? It will be easier for us to work on it this way.

**Comment by lde-avaleo** [comment] 2019-02-15 11:40
Hi Olga,

Step to reproduce:

- Run rabbitmq instance e.g. docker
`docker run -d --name rabbitmq -p 5672:5672 -e RABBITMQ_DEFAULT_USER=user -e RABBITMQ_DEFAULT_PASS=password rabbitmq:3`

- Place given test under `spring-cloud-contract/tests/samples-messaging-amqp/src/test/groovy/com/example`
```
package com.example

import static com.toomuchcoding.jsonassert.JsonAssertion.assertThatJson
import static org.assertj.core.api.Assertions.assertThat
import static org.springframework.cloud.contract.verifier.messaging.util.ContractVerifierMessagingUtil.headers

import com.jayway.jsonpath.DocumentContext
import com.jayway.jsonpath.JsonPath
import javax.inject.Inject
import org.springframework.boot.test.context.SpringBootContextLoader
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.cloud.contract.verifier.messaging.boot.AutoConfigureMessageVerifier
import org.springframework.cloud.contract.verifier.messaging.internal.ContractVerifierMessage
import org.springframework.cloud.contract.verifier.messaging.internal.ContractVerifierMessaging
import org.springframework.cloud.contract.verifier.messaging.internal.ContractVerifierObjectMapper
import org.springframework.test.context.ContextConfiguration
import spock.lang.Issue
import spock.lang.Specification

@ContextConfiguration(classes = [AmqpMessagingApplication], loader = SpringBootContextLoader)
@AutoConfigureMessageVerifier
@SpringBootTest(properties = ["stubrunner.amqp.enabled=true",
		"stubrunner.amqp.mockConnection=false",
		"spring.rabbitmq.port=5672",
		"spring.rabbitmq.username=user",
		"spring.rabbitmq.password=password",
		"spring.rabbitmq.publisher-confirms=true"])
class AmqpMessagingApplicationIntegrationSpec extends Specification {

	// ALL CASES
	@Inject
	ContractVerifierMessaging contractVerifierMessaging
	@Inject
	ContractVerifierObjectMapper contractVerifierObjectMapper

	@Issue("859")
	def "should send message into real rabbitmq instance using non transacted channel"() {
		given:
			ContractVerifierMessage inputMessage = contractVerifierMessaging.create(
					"{\"name\":\"foo2\"}"
					, headers()
					.header("contentType", "application/json")
					.header("amqp_replyTo", "amq.rabbitmq.reply-to")
					.header("bill", "bill")
			)
		when:
			contractVerifierMessaging.send(inputMessage, "input")
		then:
			ContractVerifierMessage response = contractVerifierMessaging.receive("")
			assertThat(response).isNotNull()
			assertThat(response.getHeader("contentType")).isNotNull()
			assertThat(response.getHeader("contentType").toString()).
					isEqualTo("application/json")
		and:
			DocumentContext parsedJson = JsonPath.parse(contractVerifierObjectMapper.
					writeValueAsString(response.getPayload()))
			assertThatJson(parsedJson).field("['name']").isEqualTo("foo2")
	}

}
```
 
- Run test expecting it to fail with message
```
Caused by: com.rabbitmq.client.ShutdownSignalException: channel error; protocol method: #method<channel.close>(reply-code=406, reply-text=PRECONDITION_FAILED - cannot switch from tx to confirm mode, class-id=85, method-id=10)
	at com.rabbitmq.client.impl.ChannelN.asyncShutdown(ChannelN.java:516) ~[amqp-client-5.4.3.jar:5.4.3]
	at com.rabbitmq.client.impl.ChannelN.processAsync(ChannelN.java:346) ~[amqp-client-5.4.3.jar:5.4.3]
	at com.rabbitmq.client.impl.AMQChannel.handleCompleteInboundCommand(AMQChannel.java:178) ~[amqp-client-5.4.3.jar:5.4.3]
	at com.rabbitmq.client.impl.AMQChannel.handleFrame(AMQChannel.java:111) ~[amqp-client-5.4.3.jar:5.4.3]
	at com.rabbitmq.client.impl.AMQConnection.readFrame(AMQConnection.java:670) ~[amqp-client-5.4.3.jar:5.4.3]
	at com.rabbitmq.client.impl.AMQConnection.access$300(AMQConnection.java:48) ~[amqp-client-5.4.3.jar:5.4.3]
	at com.rabbitmq.client.impl.AMQConnection$MainLoop.run(AMQConnection.java:597) ~[amqp-client-5.4.3.jar:5.4.3]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]


java.lang.RuntimeException: java.lang.NullPointerException

	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:139)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:102)
	at org.springframework.cloud.contract.verifier.messaging.internal.ContractVerifierMessaging.send(ContractVerifierMessaging.java:40)
	at com.example.AmqpMessagingApplicationIntegrationSpec.should send message into real rabbitmq instance using non transacted channel(AmqpMessagingApplicationIntegrationSpec.groovy:63)
Caused by: java.lang.NullPointerException
	at org.springframework.amqp.rabbit.connection.PublisherCallbackChannelImpl.shutdownCompleted(PublisherCallbackChannelImpl.java:828)
	at org.springframework.amqp.rabbit.connection.PublisherCallbackChannelImpl.shutdownCompleted(PublisherCallbackChannelImpl.java:1107)
	at com.rabbitmq.client.impl.ShutdownNotifierComponent.addShutdownListener(ShutdownNotifierComponent.java:55)
	at org.springframework.amqp.rabbit.connection.PublisherCallbackChannelImpl.<init>(PublisherCallbackChannelImpl.java:128)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.doCreateBareChannel(CachingConnectionFactory.java:665)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.createBareChannel(CachingConnectionFactory.java:637)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getCachedChannelProxy(CachingConnectionFactory.java:607)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.getChannel(CachingConnectionFactory.java:498)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory.access$1600(CachingConnectionFactory.java:101)
	at org.springframework.amqp.rabbit.connection.CachingConnectionFactory$ChannelCachingConnectionProxy.createChannel(CachingConnectionFactory.java:1331)
	at org.springframework.cloud.contract.verifier.messaging.amqp.SpringAmqpStubMessages.send(SpringAmqpStubMessages.java:136)
	... 3 more
```

- Investigate SpringAmqpStubMessages#send(Message message, String destination) method playing around code below
```
try {
	((ChannelAwareMessageListener) messageListener).onMessage(message,
				listenerContainer.getConnectionFactory().createConnection()
						.createChannel(true));
	}
	catch (Exception e) {
		throw new RuntimeException(e);
	}
}
```
We are creating channel using transactional always set to true which doesn't work with publisher-confirms mode.
Is it necessary to trigger stub messages within transaction? If not just change it to false otherwise we need to check what kind of mode rabbitmq connectionFactory is working with.

regards,
Lukasz

**Comment by marcingrzejszczak** [comment] 2019-02-15 14:00
Hi Lukasz. Could you please create a GitHub project that replicates this problem? I'm not saying that what you suggested won't replicate it, but often those tiny details matter, so it's better to have an isolated case. Thanks.

**Comment by lde-avaleo** [comment] 2019-02-18 12:30
Hi Marcin,

You'll find test case under https://github.com/lde-avaleo/spring-cloud-contract-issue-859

gradle clean check should do the work

regards,
Lukasz

**Comment by marcingrzejszczak** [comment] 2019-02-21 11:48
```
> Task :test

lde.spring.cloud.contract.issue859.AmqpMessagingTxModeSpec > should send message using non transacted channel with real rabbitmq connection FAILED
    java.lang.RuntimeException at AmqpMessagingTxModeSpec.groovy:73
        Caused by: org.springframework.amqp.AmqpIOException at AmqpMessagingTxModeSpec.groovy:73
            Caused by: java.io.IOException at AmqpMessagingTxModeSpec.groovy:73
                Caused by: com.rabbitmq.client.ShutdownSignalException at AmqpMessagingTxModeSpec.groovy:73
                    Caused by: java.io.EOFException

lde.spring.cloud.contract.issue859.AmqpMessagingConfirmModeSpec > should send message using non transacted channel into real rabbitmq instance FAILED
    java.lang.RuntimeException at AmqpMessagingConfirmModeSpec.groovy:74
        Caused by: org.springframework.amqp.AmqpIOException at AmqpMessagingConfirmModeSpec.groovy:74
            Caused by: java.io.IOException at AmqpMessagingConfirmModeSpec.groovy:74
                Caused by: com.rabbitmq.client.ShutdownSignalException at AmqpMessagingConfirmModeSpec.groovy:74
                    Caused by: java.net.SocketException
```

I can't replicate it with your sample @lde-avaleo

**Comment by lde-avaleo** [comment] 2019-02-21 12:43
I've pushed by mistake wrong rabbitmq image in docker-compose config. I've just pushed fix.
Please pull and try again.
I'm sorry for inconvienience.

**Comment by marcingrzejszczak** [comment] 2019-02-21 14:46
Thanks @lde-avaleo for the project to reproduce. I've confirmed that the bug is fixed with the fix. You can wait for the snapshots to be built and check it out yourself.

**Closed** 2019-02-21 14:46 UTC
Labels: bug
