### ISSUE TITLE
Cannot use gradle plugin with Gradle 7.0

### ISSUE THREAD

**Issue by razubuddy** [spring-cloud/spring-cloud-contract#1641] opened 2021-04-16 14:34 UTC
> Task :copyContracts FAILED

FAILURE: Build failed with an exception.

* What went wrong:
A problem was found with the configuration of task ':copyContracts' (type 'ContractsCopyTask').
  - Type 'ContractsCopyTask.Dependency' method 'toStubConfiguration()' should not be annotated with: @Internal.
    
    Reason: Input/Output annotations are ignored if they are placed on something else than a getter.
    
    Possible solutions:
      1. Remove the annotations.
      2. Rename the method.
    
    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#ignored_annotations_on_method for more details about this problem.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 9s
9 actionable tasks: 9 executed

**Comment by marcingrzejszczak** [comment] 2021-04-16 16:21
cc @shanman190

**Comment by shanman190** [comment] 2021-04-17 01:12
Duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/1636.

The fix should be available in the latest snapshot.

**Comment by marcingrzejszczak** [comment] 2021-04-19 06:46
Closing in favor of #1636

**Closed by marcingrzejszczak** 2021-04-19 06:46 UTC
Labels: waiting-for-triage
