### ISSUE TITLE
we want to use spring cloud contract test to test the behavior of the system have bad request response

### ISSUE THREAD

**Issue by DT0814** [spring-cloud/spring-cloud-contract#1390] opened 2020-04-28 05:52 UTC
we have a question.
 when we have a contract to test system have bad request.
contract like this
```
Contract.make {
    description "xxxxx."
    request {
        url ("/aaaa")
        headers {
            contentType applicationJson()
        }
        method POST()
        body(file("request.json"))
    }
    response {
        status BAD_REQUEST()
        headers {
            contentType applicationJson()
        }
        body(file("response.json"))
    }
}
```
this interface we use spring validation to check request param. 

When this exception occurs in spring validation, there is no information returned by spring validation in the `responseBody` of `mockMvc` used in contract test, but this problem does not exist when we use postman to test this interface. We try to accept the verification failure information in the controller and return the `responseEntity` without this problem. Does anyone know any other solution?

and all exception info in `ResponseOption` `statusLine` properties.

**Comment by OlgaMaciaszek** [comment] 2020-04-29 15:59
Hi, @DT0814 
Please learn how to properly [format code and logs](https://help.github.com/articles/creating-and-highlighting-code-blocks/). 
I am not sure I understand correctly what you are trying to do. 
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue. Please describe what command you run and what you expect to happen.

**Comment by spring-issuemaster** [comment] 2020-05-06 16:03
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-05-13 16:03
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-05-13 16:03 UTC
Labels: feedback-reminder, waiting for feedback
