### ISSUE TITLE
AMQP consumer-test throws StackOverflowError

### ISSUE THREAD

**Issue by jaredculp** [spring-cloud/spring-cloud-contract#1404] opened 2020-05-08 18:30 UTC
**Describe the bug**
Please provide details of the problem, including the version of Spring Cloud that you
are using. 

Reading a Gzip file with `body(fileAsBytes('input'))` allows a producer-side test to pass. Running the consumer-side test errors with:

```
2020-05-08 14:03:16.181  INFO 11492 --- [           main] dev.culp.consumer.ContractTests          : Started ContractTests in 6.438 seconds (JVM running for 10.022)



java.lang.StackOverflowError
	at org.codehaus.groovy.util.ManagedReference.get(ManagedReference.java:38)
	at org.codehaus.groovy.reflection.ClassInfo.getWeakMetaClass(ClassInfo.java:238)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClassForClass(ClassInfo.java:267)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:324)
	at org.codehaus.groovy.reflection.ClassInfo.getMetaClass(ClassInfo.java:339)
	at org.codehaus.groovy.runtime.metaclass.MetaClassRegistryImpl.getMetaClass(MetaClassRegistryImpl.java:276)
	at org.codehaus.groovy.runtime.InvokerHelper.getMetaClass(InvokerHelper.java:965)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getMetaPropertyValues(DefaultGroovyMethods.java:534)
	at org.codehaus.groovy.runtime.DefaultGroovyMethods.getProperties(DefaultGroovyMethods.java:553)
	at groovy.json.DefaultJsonGenerator.getObjectProperties(DefaultJsonGenerator.java:242)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:236)
	at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
	at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:237)
	at groovy.json.DefaultJsonGenerator.writeMapEntry(DefaultJsonGenerator.java:387)
	at groovy.json.DefaultJsonGenerator.writeMap(DefaultJsonGenerator.java:375)
	at groovy.json.DefaultJsonGenerator.writeObject(DefaultJsonGenerator.java:237)
	
// etc
```

**Sample**
If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

https://github.com/jaredculp/spring-cloud-contract-amqp/commit/16b0997e583d165089bab96d8888785ba3efab30

**Comment by jaredculp** [comment] 2020-05-11 14:49
Possibly due to https://github.com/spring-cloud/spring-cloud-contract/blob/master/spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerExecutor.java#L259 trying to parse the raw message body as a JSON object?

**Comment by santiagovm** [comment] 2020-09-09 05:31
same problem here

**Comment by marcingrzejszczak** [comment] 2021-03-08 14:24
Hey @jaredculp , I've taken your sample and did the following upgrades:

```

      <plugin>
        <groupId>org.springframework.cloud</groupId>
        <artifactId>spring-cloud-contract-maven-plugin</artifactId>
        <version>2.2.6</version>
        <extensions>true</extensions>
        <configuration>
          <testFramework>JUNIT5</testFramework>
          <baseClassForTests>dev.culp.producer.Base</baseClassForTests>
        </configuration>
      </plugin>
```

Spring Boot got bumped to `2.3.9.RELEASE`. I've successfully generated producer tests and stubs:

```
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.985 s - in dev.culp.producer.ContractVerifierTest
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- spring-cloud-contract-maven-plugin:2.2.6.RELEASE:generateStubs (default-generateStubs) @ producer ---
[INFO] Files matching this pattern will be excluded from stubs generation []
[INFO] Building jar: /home/marcin/repo/contract-issues/spring-cloud-contract-amqp/producer/target/producer-0.0.1-SNAPSHOT-stubs.jar
```

The test looks like this:

```java
package dev.culp.producer;

import dev.culp.producer.Base;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import javax.inject.Inject;
import org.springframework.cloud.contract.verifier.messaging.internal.ContractVerifierObjectMapper;
import org.springframework.cloud.contract.verifier.messaging.internal.ContractVerifierMessage;
import org.springframework.cloud.contract.verifier.messaging.internal.ContractVerifierMessaging;

import static org.springframework.cloud.contract.verifier.assertion.SpringCloudContractAssertions.assertThat;
import static org.springframework.cloud.contract.verifier.util.ContractVerifierUtil.*;
import static org.springframework.cloud.contract.verifier.messaging.util.ContractVerifierMessagingUtil.headers;
import static org.springframework.cloud.contract.verifier.util.ContractVerifierUtil.fileToBytes;

@SuppressWarnings("rawtypes")
public class ContractVerifierTest extends Base {
	@Inject ContractVerifierMessaging contractVerifierMessaging;
	@Inject ContractVerifierObjectMapper contractVerifierObjectMapper;

	@Test
	public void validate_shouldProduceFoo() throws Exception {
		// when:
			foo();

		// then:
			ContractVerifierMessage response = contractVerifierMessaging.receive("foo");
			assertThat(response).isNotNull();

		// and:
			assertThat(response.getHeader("GZIP-Compression")).isNotNull();
			assertThat(response.getHeader("GZIP-Compression").toString()).isEqualTo("true");

		// and:
			assertThat(response.getPayloadAsByteArray()).isEqualTo(fileToBytes(this, "shouldProduceFoo_response_foo.json.gz"));
	}

}
```

can you double check that the problem is indeed gone?

**Comment by spring-cloud-issues** [comment] 2021-03-15 14:28
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-03-22 14:28
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-03-22 14:28 UTC
Labels: feedback-reminder, waiting for feedback
