### ISSUE TITLE
Please add option to fail if contracts yaml file can't be parsed

### ISSUE THREAD

**Issue by OctoOsmo** [spring-cloud/spring-cloud-contract#1681] opened 2021-07-22 15:55 UTC
When I have any misprint or error in my yaml contract I get a warning: "Error Processing yaml file. Skipping Contract Generation". It's nice. 
But if I run contract test in my build I won't get failed build which would be nice. 

I think the best solution is to add option flag which would allow to throw an exception in YamlContractConverter after line 50;

If you find this idea acceptable I can implement it and create PR with this feature.

**Comment by marcingrzejszczak** [comment] 2021-07-22 16:03
Duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/1675. Be my guest to apply a PR that has the option for both maven and gradle to throw an exception whenever a contract conversion faills.

**Closed by marcingrzejszczak** 2021-07-22 16:03 UTC
Labels: waiting-for-triage
