### ISSUE TITLE
Provider side picks up the default profile yaml

### ISSUE THREAD

**Issue by smfaizalkhan** [spring-cloud/spring-cloud-contract#1890] opened 2023-04-17 17:20 UTC
**Provider side picks up the default profile yaml**
Provider side picks up the default profile yaml and tries to run it in consumer side 

**Sample**
 default profile and test profile on provider side
 
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/22238550/232559610-3fe48e86-79f0-40ab-90f0-fa224bce7cf9.png">

On the consumer side

<img width="1181" alt="image" src="https://user-images.githubusercontent.com/22238550/232561316-246e18b7-774d-499b-b9d5-062ad329c99e.png">

Instead of picking the VM it picks the tcp (Provider side application yaml)

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/22238550/232561595-bec26307-c7a3-4d3b-8d1e-f25618ce8d7a.png">

Please adivce @marcingrzejszczak  @OlgaMaciaszek

**Comment by marcingrzejszczak** [comment] 2023-04-19 09:00
I don't think this is a problem with Spring Cloud Contract per se because we do not do anything with profiles. Maybe it's a problem with Spring Boot test support? What if instead of using the test profile you would pass the properties using manually through `SpringBootTest` ?

**Comment by marcingrzejszczak** [comment] 2023-04-19 09:36
Please provide the properties manually ` @SpringBootTest(properties=...)`

**Comment by smfaizalkhan** [comment] 2023-04-19 09:47
Hi @marcingrzejszczak 

No Luck either

<img width="892" alt="image" src="https://user-images.githubusercontent.com/22238550/233036818-c6dceacf-e1d1-4fc9-b9e2-01612c41c84b.png">

**Comment by marcingrzejszczak** [comment] 2023-04-19 09:48
I don't understand why, I guess you will need to file an issue in Spring Boot. Spring Cloud Contract does not modify the default Spring Boot test configuration mechanism. I'm closing this issue but feel free to open one in Spring Boot with a reproducer and a link to this issue.

**Closed by marcingrzejszczak** 2023-04-19 09:48 UTC
Labels: feedback-provided
