### ISSUE TITLE
Contract tests stopped working after upgrading to Spring Boot 2.4 and Spring Cloud 2020.0.1

### ISSUE THREAD

**Issue by vprudnikov** [spring-cloud/spring-cloud-contract#1606] opened 2021-01-29 11:09 UTC
Hello,

I upgraded my app:
* Spring boot 2.3.3.RELEASE -> 2.4.2
* Spring cloud Hoxton.SR7 -> 2020.0.1

**After this upgrade, all contract tests stopped working: methods annotated with `@StreamListener` are not called any longer.**

I see that these annotations became deprecated, but I assume that they should still work.
I have no error in logs. Contract stubs are correctly resolved and downloaded from the remote repo. However, stream listeners are just silently ignored.

Did I miss anything?
Thank you in advance.

**Comment by marcingrzejszczak** [comment] 2021-02-01 10:52
Can you please create a sample that replicates this issue?

**Comment by vprudnikov** [comment] 2021-02-01 11:23
@marcingrzejszczak, unfortunately, I'm working on a big project so it won't be possible to extract it...

I don't think we are using anything special. This is our example of a listener:

````

@Component
@RequiredArgsConstructor
public class ExternalEventsConsumer {

private final TargetEventsConsumer target;

@StreamListener(target = "someInput", condition = "headers['type']=='SomeEvent'")
    @Override
    public void consumeSomeEvent(SomeEvent event) {
        target.consumeSomeEvent(event);
    }

...

```

This is how we test it:

```
...
@AutoConfigureStubRunner(ids = "company.package:artifact:+:stubs")
class SomeContractSpec extends Specification {

    @Autowired
    TargetEventsConsumer targetEventsConsumer
    @Autowired
    StubTrigger stubTrigger

    ...

    def "Receives some event"() {
        when:
        stubTrigger.trigger("some.event.created")

        then:
        1 * targetEventsConsumer.consumeSomeEvent(new SomeEvent())
    }

```

**Comment by davidmelia** [comment] 2021-02-01 15:09
@vprudnikov @marcingrzejszczak  is this a duplicate of my issue in https://github.com/spring-cloud/spring-cloud-contract/issues/1603 - I have an example project

**Comment by marcingrzejszczak** [comment] 2021-02-02 12:21
@davidmelia yeah it seems so. I'm closing this one then.

**Closed by marcingrzejszczak** 2021-02-02 12:21 UTC
Labels: feedback-provided

**Comment by vprudnikov** [comment] 2021-04-08 13:03
@marcingrzejszczak , could you please help me? I see that the referenced issue is closed, however, It doesn't work on my side.

spring-boot-starter-parent: 2.4.4
spring-cloud-dependencies: 2020.0.2

maven dependencies:
```
        <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud-dependencies.version}</version>
                <type>pom</type>
                <scope>import</scope>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
        </dependency>

        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-contract-verifier</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-contract-stub-runner</artifactId>
            <scope>test</scope>
        </dependency>

```

When I add just this
```
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-stream</artifactId>
    <type>test-jar</type>
    <scope>test</scope>
    <classifier>test-binder</classifier>
    <optional>true</optional>
</dependency>
```
then my project cannot compile: `java: package org.springframework.cloud.stream.test.binder does not exist`

When I add the following
```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-support</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream</artifactId>
            <type>test-jar</type>
            <scope>test</scope>
            <classifier>test-binder</classifier>
            <optional>true</optional>
        </dependency>
```

then the application context cannot start:
```
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.stream.binder.test.InputDestination' available
```

**Comment by marcingrzejszczak** [comment] 2021-04-08 14:12
this shouldn't be added 

```
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-stream-test-support</artifactId>
            <scope>test</scope>
        </dependency>
```

@olegz do you see what the problem might be?

**Comment by vprudnikov** [comment] 2021-04-08 14:54
@marcingrzejszczak it looks like I'm using `org.springframework.cloud.stream.test.binder.MessageCollector` (which leads to compilation error):

```
    private final Processor processor;
    private final MessageCollector collector;

...
var msg = collector.forChannel(processor.invoicingOutput()).poll();
...
processor.invoicingInput().send(msg);
...
```

Maybe I should modify this code somehow?

**Comment by marcingrzejszczak** [comment] 2021-04-08 15:33
You should not be using message collector. It's in the deprecated test module

**Comment by vprudnikov** [comment] 2021-04-08 16:33
@marcingrzejszczak thanks for a quick reply!
Could you please suggest the correct replacement for the `MessageCollector`?

**Comment by vprudnikov** [comment] 2021-04-08 19:10
@marcingrzejszczak , I figured out that I should have used the `OutputDestination` class. However, my code is still not working after the replacement :(

my test code:
```
...
@Autowired
OutputDestination output
...
output.receive(1000L, "invoicingOutput")
...
```

my test configuration:
```
spring:
  cloud:
    stream:
      bindings:
        invoicingOutput:
          destination: invoicing
        invoicingInput:
          destination: invoicing
          group: invoicing
      kafka:
        binder:
          headers:
            - type
            - userId
            - roleId
```

However, the test doesn't start showing the following in logs:
```
2021-04-08 20:58:30.191  WARN 19944 --- [| adminclient-1] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-04-08 20:58:30.294  WARN 19944 --- [| adminclient-1] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
2021-04-08 20:58:30.500  WARN 19944 --- [| adminclient-1] org.apache.kafka.clients.NetworkClient   : [AdminClient clientId=adminclient-1] Connection to node -1 (localhost/127.0.0.1:9092) could not be established. Broker may not be available.
```

@marcingrzejszczak do you know what else I missed?
Thank you.

**Comment by vprudnikov** [comment] 2021-04-08 19:30
@marcingrzejszczak I figured out that I should use the `OutputDestination` class and `@Import(TestChannelBinderConfiguration.class)`

**Comment by prasadchavan231989** [comment] 2021-06-14 15:29
Hi @vprudnikov , 
I am currently facing similar issues which you have faced earlier, as mentioned in the post. I am having trouble to find a replacement of MessageCollector for my legacy annotation based cloud stream approach and as a result existing integration tests are failing.
Let me know if you have found an approach to overcome this.

**Comment by vprudnikov** [comment] 2021-06-14 20:59
Hi @prasadchavan231989 

You should import `TestChannelBinderConfiguration` toy our test context:
```
@Configuration
@Import(TestChannelBinderConfiguration.class)
public class YourTestConfig {
}
```

The `OutputDestination` class should be used:
```
@Autowired
OutputDestination output
...
... = output.receive(timeout, "your_destination_name")
```

**Comment by prasadchavan231989** [comment] 2021-06-15 08:23
Hi @vprudnikov , 
As per your comment on 8th April-- 'I see that OutputDestination#messageQueues contains the 'invoicing' binding (NOT the "invoicingOutput" according to the configuration)'

Did you find a solution for above --- as using the destination name like 'invoicing'  instead of 'invoicingOutput' would defeat the purpose of loose coupling with messagerbroker(like rabbitMQ etc).

Thank you for your quick response.

**Comment by vprudnikov** [comment] 2021-06-15 09:13
@prasadchavan231989 , no, I didn't find a solution for that, so I use a destination name.

I hope  @marcingrzejszczak can take a look at https://github.com/spring-cloud/spring-cloud-contract/issues/1606#issuecomment-816098326

**Comment by marcingrzejszczak** [comment] 2021-06-15 09:14
Sorry, yes please open a new bug with a sample to reproduce it.

**Comment by venkatesh010** [comment] 2022-06-17 13:07
> this shouldn't be added
> 
> ```
>         <dependency>
>             <groupId>org.springframework.cloud</groupId>
>             <artifactId>spring-cloud-stream-test-support</artifactId>
>             <scope>test</scope>
>         </dependency>
> ```
> 
> @olegz do you see what the problem might be?

@marcingrzejszczak , but removing test support causes message collector to break at other integration tests, and spring cloud stream alone doesn't resolve message collector

So in a way, is there a backward compatible way, to run, both contract verifier and other integration tests using message collector?
