### ISSUE TITLE
Property to skip tests but generate stubs

### ISSUE THREAD

**Issue by rorwalsh** [spring-cloud/spring-cloud-contract#966] opened 2019-03-21 18:21 UTC
Would it be possible to add a property that allows the tests to be ignored but the stubs to still be generated?

The scenario I'm trying to address is that we agree the contracts early in a sprint so that the UI developers can code against it. However since the server side code is not yet written the tests obviously fail so we have to skip tests which is not ideal as this skips all tests. 

The **ignored** property allows skipping of an individual contract but unfortunately does not generate the stubs either.

**Comment by marcingrzejszczak** [comment] 2019-03-22 10:54
Duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/881

**Closed by marcingrzejszczak** 2019-03-22 10:54 UTC
Labels: waiting-for-triage
