### ISSUE TITLE
SCC Gradle plugin when plugin is applied, a plugin that does "tasks.all" before.

### ISSUE THREAD

**Issue by jonyto123** [spring-cloud/spring-cloud-contract#2116] opened 2024-06-20 12:47 UTC
When a plugin that uses the tasks.all configuration is applied before the SCC Gradle plugin, the SCC plugin fails with the following error:
```
An exception occurred applying plugin request [id: 'org.springframework.cloud.contract', version: '4.1.3']
> Failed to apply plugin 'org.springframework.cloud.contract'.
   > Could not create task ':copyContracts'.
      > Configuration with name 'contractTestGeneratorRuntimeClasspath' not found.
```

To reproduce the error, clone the following small project and run ./gradlew tasks:
https://github.com/jonyto123/scc-configuration-bug/

**Comment by marcingrzejszczak** [comment] 2024-06-21 10:08
@shanman190 :pray:

**Comment by shanman190** [comment] 2024-06-21 14:19
Alright, with some contorting I think we could work around the issue, but at the moment from a Gradle perspective the issue is with that `TaskContainer.all(..)` invocation more so. `all` eagerly creates any task that is registered and Gradle strongly encourages folks to avoid eagerly creating tasks which transitively means avoiding methods such as `all`. 

In the SCC case, I'd have to delay registering tasks until the test suite is created, then turn around and reach back inside of it to configure the Gradle configurations, and then the tasks. None of which would be necessary if the eager task creation was fixed which would also improve the configuration phase performance of your Gradle build.

Is it possible to fix the upstream plugin to be more Gradle friendly?

**Comment by jonyto123** [comment] 2024-06-21 16:21
Fixed the upstream plugin by switching from using `.all { }` to ` .configureEach { }` thanks a lot for the hints. 
So for my case, I think i ll be good for now.

**Comment by shanman190** [comment] 2024-06-21 16:27
Thanks for the update, @jonyto123!

@marcingrzejszczak, I think we can go ahead and close this now.

**Comment by marcingrzejszczak** [comment] 2024-06-27 12:17
Thank you @jonyto123 and @shanman190 !

**Closed by marcingrzejszczak** 2024-06-27 12:17 UTC
Labels: waiting-for-triage
