### ISSUE TITLE
Serving PDF is not possible

### ISSUE THREAD

**Issue by abbasadel** [spring-cloud/spring-cloud-contract#713] opened 2018-08-16 15:12 UTC
Hi,

I'm trying to build the following contract to download a PDF file.

```
Contract.make {
    request {
        method GET()
        url "/download/response.pdf"
        
    }

    response {
        status 200
        body(file('files/response.pdf'))
        headers {
            contentType(applicationOctetStream())
            header("Content-Disposition", "attachment; filename=\"response.pdf\"")
        }
    }
}
```

I noticed that the generated json file contains the content of the PDF and when running the stub in standalone mode it always fails because ```files/response.pdf``` can't be found.

I tried to include the pdf file in the stub using maven assembly plugin as [described here](https://cloud.spring.io/spring-cloud-contract/multi/multi__spring_cloud_contract_stub_runner.html#publishing-stubs-as-jars) then I got this error:
 
```
HTTP ERROR 500
Problem accessing /download/response.pdf. Reason:

    Server Error
Caused by:
wiremock.com.github.jknack.handlebars.HandlebarsException: inline@5e50c66e:324:169: found: '&'
?6*?&#3;28??&#11;R%^?{?UPD??&#21;?&#5;??6m5nV?]56???.&gt;XjB?T?y????J?&#127;???&#30;?`.???&#14;?C?%l?&#26;??&#28;Y??^*.,v?[?????W?zÅ??f?????&apos;?&lt;???&#127;Q?a?_{{{_&#11;[????sS???&#27;????????+n`mW?????v?&#30;????????(??9X??M??l?g0?#?????}o???%zW?D&#21;??!?y??l??;ciK??Uqm?}&#23;e??&#15;?+.?&#2;? &#23;????~&#31;&#21;&#15;&#15;&#127;?}??jnb?]?&#3;4???&#29;?}?_?*|=???Na{}y????j?4?v?y4???,|)o~?PX_Y&#28;??4??????S&#11;Ko&gt;&#20;
                                                                                                                                                                         ^

	at wiremock.com.github.jknack.handlebars.internal.HbsErrorReporter.syntaxError(HbsErrorReporter.java:93)
	at wiremock.org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
	at wiremock.com.github.jknack.handlebars.internal.HbsParserFactory$2.notifyListeners(HbsParserFactory.java:148)
	at wiremock.org.antlr.v4.runtime.Lexer.nextToken(Lexer.java:168)
	at wiremock.org.antlr.v4.runtime.BufferedTokenStream.fetch(BufferedTokenStream.java:185)
	at wiremock.org.antlr.v4.runtime.BufferedTokenStream.sync(BufferedTokenStream.java:168)
	at wiremock.org.antlr.v4.runtime.BufferedTokenStream.consume(BufferedTokenStream.java:152)
	at wiremock.org.antlr.v4.runtime.Parser.consume(Parser.java:593)
	at wiremock.org.antlr.v4.runtime.Parser.match(Parser.java:226)
	at wiremock.com.github.jknack.handlebars.internal.HbsParser.sexpr(HbsParser.java:884)
	at wiremock.com.github.jknack.handlebars.internal.HbsParser.tvar(HbsParser.java:1261)
	at wiremock.com.github.jknack.handlebars.internal.HbsParser.statement(HbsParser.java:350)
	at wiremock.com.github.jknack.handlebars.internal.HbsParser.body(HbsParser.java:222)
	at wiremock.com.github.jknack.handlebars.internal.HbsParser.template(HbsParser.java:165)
	at wiremock.com.github.jknack.handlebars.internal.HbsParserFactory$1.parse(HbsParserFactory.java:84)
	at wiremock.com.github.jknack.handlebars.cache.NullTemplateCache.get(NullTemplateCache.java:54)
	at wiremock.com.github.jknack.handlebars.Handlebars.compile(Handlebars.java:414)
	at wiremock.com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:384)
	at wiremock.com.github.jknack.handlebars.Handlebars.compileInline(Handlebars.java:368)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.uncheckedCompileTemplate(ResponseTemplateTransformer.java:161)
	at com.github.tomakehurst.wiremock.extension.responsetemplating.ResponseTemplateTransformer.transform(ResponseTemplateTransformer.java:111)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.applyTransformations(InMemoryStubMappings.java:91)
	at com.github.tomakehurst.wiremock.stubbing.InMemoryStubMappings.serveFor(InMemoryStubMappings.java:72)
	at com.github.tomakehurst.wiremock.core.WireMockApp.serveStubFor(WireMockApp.java:164)
	at com.github.tomakehurst.wiremock.http.StubRequestHandler.handleRequest(StubRequestHandler.java:50)
	at com.github.tomakehurst.wiremock.http.AbstractRequestHandler.handle(AbstractRequestHandler.java:44)
	at com.github.tomakehurst.wiremock.servlet.WireMockHandlerDispatchingServlet.service(WireMockHandlerDispatchingServlet.java:108)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at wiremock.org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:812)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:587)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127)
	at wiremock.org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at wiremock.org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061)
	at wiremock.org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at wiremock.org.eclipse.jetty.servlets.gzip.GzipHandler.handle(GzipHandler.java:479)
	at wiremock.org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:110)
	at wiremock.org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at wiremock.org.eclipse.jetty.server.Server.handle(Server.java:499)
	at wiremock.org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at wiremock.org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:258)
	at wiremock.org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:544)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635)
	at wiremock.org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555)
	at java.lang.Thread.run(Thread.java:748)
```
Any good ideas of serving a pdf or any non-textual file possible with Spring Cloud Contract?

Thanks,

**Comment by marcingrzejszczak** [comment] 2018-08-16 15:18
We don't support it properly yet. 

Duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/664

**Closed by marcingrzejszczak** 2018-08-16 15:18 UTC
