### ISSUE TITLE
Stub runner: No request logging from version 4.0.0

### ISSUE THREAD

**Issue by Patresss** [spring-cloud/spring-cloud-contract#1932] opened 2023-08-23 14:59 UTC
**Describe the bug**
I'm using the Docker image of the stub runner:
```
FROM springcloud/spring-cloud-contract-stub-runner:4.0.3

ARG IDS="test"
ENV STUBRUNNER_REPOSITORY_ROOT="stubs://file://contracts"
ENV STUBRUNNER_STUBS_MODE="LOCAL"
ENV STUBRUNNER_GENERATE_STUBS="TRUE"
ENV STUBRUNNER_IDS="${IDS}:+:stubs:8080"

COPY ./contracts /contracts/
```

In version 3.1.8, when I sent any request to the stub runner, I could see the request/response body in the logs. For example:
```
2023-08-23 16:29:54   },
2023-08-23 16:29:54   "transformers" : [ "response-template", "spring-cloud-contract" ]
2023-08-23 16:29:54 }
2023-08-23 16:29:54 
2023-08-23 16:29:54 Response:
2023-08-23 16:29:54 HTTP/1.1 200
2023-08-23 16:29:54 Content-Type: [text/xml]
2023-08-23 16:29:54 Matched-Stub-Id: [94f62c49-7019-4d9d-aced-6db0ecb996c5]
2023-08-23 16:29:54 
2023-08-23 16:29:54
```

In version 4.0.3 this is no longer the case, and after starting the application, I only see 
```
...
2023-08-23 16:46:33 2023-08-23T14:46:33.361Z  INFO 7 --- [           main] o.s.c.c.s.server.StubRunnerBoot          : Started StubRunnerBoot in 24.966 seconds (process running for 53.996)

```
and nothing more when I send a request. The application functions the same way, just without the logs.

I'm not sure if this is a bug or if there's an environment variable that needs to be enabled for this. I've tried the ones below, but they didn't help:
```
ENV STUBRUNNER_OUTPUT_ENABLED="true"
ENV STUBRUNNER_DEBUG="true"
ENV LOGGING_LEVEL_COM_GITHUB_TOMAKEHURST_WIREMOCK="DEBUG"
ENV LOGGING_LEVEL_WIREMOCK_ORG="DEBUG"
ENV LOGGING_LEVEL_WIREMOCK="DEBUG"
ENV LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB="DEBUG"
```

**Sample**

Add any stub to the "contracts" folder and run the stub-runner in version 4.0.3
```
FROM springcloud/spring-cloud-contract-stub-runner:4.0.3

ARG IDS="test"
ENV STUBRUNNER_REPOSITORY_ROOT="stubs://file://contracts"
ENV STUBRUNNER_STUBS_MODE="LOCAL"
ENV STUBRUNNER_GENERATE_STUBS="TRUE"
ENV STUBRUNNER_IDS="${IDS}:+:stubs:8080"

COPY ./contracts /contracts/
```

```
docker build -t contract .          
docker run -dp 127.0.0.1:8080:8080 contract
```

Result: request/response bodies are not visible in the application logs
Expected result: request/response bodies are visible in the application logs

When we change the version to 3.1.8, the logs are visible.

**Comment by marcingrzejszczak** [comment] 2023-09-05 16:46
duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/1916

**Closed by marcingrzejszczak** 2023-09-05 16:46 UTC
Labels: waiting-for-triage
