### ISSUE TITLE
Add filtering option for consumers that are retrieving stubs from producers jar containing other consumers

### ISSUE THREAD

**Issue by anikitchuk** [spring-cloud/spring-cloud-contract#655] opened 2018-05-11 15:57 UTC
When common repository publishes stub-jars to Nexus/Artifactory by producers/messaging topics better to have an option that allows consumers to filter and process the stubs that belong only to itself.

**Comment by marcingrzejszczak** [comment] 2018-05-11 16:03
Duplicate of the `stubsPerConsumer` feature

**Closed by marcingrzejszczak** 2018-05-11 16:03 UTC
Labels: duplicate
