### ISSUE TITLE
Messaging with Spring Cloud Stream fail

### ISSUE THREAD

**Issue by ricadro** [spring-cloud/spring-cloud-contract#1798] opened 2022-06-13 08:38 UTC
When I use Messaging with Spring Cloud Stream, there is a problem, I know that the message is sent successfully in generate class through debug 
```java
contractVerifierMessaging.send(inputMessage, "xxx"); 
```
But my application does not receive the message,This is what happened after I upgraded Spring Cloud Contract to 3.0.3

**Comment by marcingrzejszczak** [comment] 2022-06-13 08:52
Can you please answer all the required questions described in the issue template? For your convenience let me paste it here

> **Describe the bug**
> Please provide details of the problem, including the version of Spring Cloud that you
are using. 
> 
> **Sample**
> If possible, please provide a test case or sample application that reproduces
the problem. This makes it much easier for us to diagnose the problem and to verify that
we have fixed it.

Can you also check this sample https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.1.x/producer_kafka_middleware where we use e.g. Kafka via TestContainers for contract tests and try to do the same?

**Comment by marcingrzejszczak** [comment] 2022-06-13 10:01
Can you also check this sample https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.1.x/producer_kafka_middleware where we use e.g. Kafka via TestContainers for contract tests and try to do the same?

You can also check this example https://github.com/spring-cloud-samples/spring-cloud-contract-samples/tree/3.1.x/producer_kafka for the Spring Cloud Stream test framework example

**Comment by ricadro** [comment] 2022-06-15 06:19
I try to do the same ,but the result is different

**Comment by marcingrzejszczak** [comment] 2022-06-15 08:05
It will be very hard to help you without any code... 

Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem rather than pasted code? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.

**Comment by spring-cloud-issues** [comment] 2022-06-22 08:09
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2022-06-29 08:09
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2022-06-29 08:09 UTC
Labels: waiting for feedback, feedback-reminder
