### ISSUE TITLE
Allow build not to fail on producer side when no contracts were found

### ISSUE THREAD

**Issue by MoOFueL** [spring-cloud/spring-cloud-contract#712] opened 2018-08-16 10:17 UTC
**Enhancement**

If SCC maven(did not test gradle) plugin does not find contracts in remote(i.e. Pact Broker) - build fails.
It would be good to introduce plugin property to allow build to pass if no contracts were found.

**Comment by marcingrzejszczak** [comment] 2018-08-22 14:08
@MoOFueL Can you please present the logs with the exception you're seeing?

**Comment by marcingrzejszczak** [comment] 2019-01-21 16:07
ping @MoOFueL ?

**Comment by MoOFueL** [comment] 2019-01-21 22:40
@marcingrzejszczak Sorry for not replying at the time. That was long ago, so no, i have no logs available now.
But if this helps, receipt for error was to tell scc producer to look for its contracts in pact broker and there were no registered pacts.

**Comment by marcingrzejszczak** [comment] 2019-01-22 07:20
@MoOFueL since there are no logs or anything to reproduce the issue, I'll close this issue for now and we can consider reopening once we have some more information

**Closed by marcingrzejszczak** 2019-01-22 07:20 UTC
Labels: enhancement, feedback-provided
