### ISSUE TITLE
It is not possible to retrieve url as String (spring-cloud-contract-tools 2.2.0.RC2)

### ISSUE THREAD

**Issue by ensigner** [spring-cloud/spring-cloud-contract#1371] opened 2020-04-01 09:27 UTC
In spring cloud contract (groovy DSL) file I have issues with extracting a segment of request URL to use it as a parameter of in response body
```
package contracts

import org.springframework.cloud.contract.spec.Contract

Contract.make {
    description "Should return OK "
    request {
        url "/discovery.svc/something(\'${value(consumer(regex(".*")),
                                    producer('defaultSomething'))}\')"
        method GET()
    }

    response {

        status 200
        body :
                value(
                        consumer(file("response/defaultSomething.xml").file.write(
                                String.format("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                                        "<entry xmlns:metadata=\"http://docs.oasis-open.org/odata/ns/metadata\" xmlns:data=\"http://docs.oasis-open.org/odata/ns/data\" xmlns=\"http://www.w3.org/2005/Atom\" metadata:context=\"http://localhost:8082/discovery.svc/\$metadata#Environment/ContentServiceCapability\" xml:base=\"http://localhost:8082/discovery.svc\">\n" +
                                        "    <id>http://localhost:8082/discovery.svc/something('%1\$s')</id>\n" +
                                        "    <title></title>\n" +
                                        "    <summary></summary>\n" +
                                        "    <updated>2020-03-23T15:19:53.272668900Z</updated>\n" +
                                        "    <author>\n" +
                                        "        <name>SDL OData v4 framework</name>\n" +
                                        "    </author>\n" +
                                        "    <link rel=\"edit\" title=\"ContentServiceCapability\" href=\"something('%1\$s')\"></link>\n" +
                                        "    <link rel=\"http://docs.oasis-open.org/odata/ns/related/Environment\" type=\"application/atom+xml;type=entry\" title=\"Environment\" href=\"something('%1\$s')/Environment\"></link>\n" +
                                        "    <link rel=\"http://docs.oasis-open.org/odata/ns/relatedlinks/Environment\" type=\"application/xml\" title=\"Environment\" href=\"something('%1\$s')/Environment/\$ref\"></link>\n" +
                                        "    <category scheme=\"http://docs.oasis-open.org/odata/ns/scheme\" term=\"#Tridion.WebDelivery.Platform.ContentServiceCapability\"></category>\n" +
                                        "    <content type=\"application/xml\">\n" +
                                        "        <metadata:properties>\n" +
                                        "            <data:id>%1\$s</data:id>\n" +
                                        "            <data:LastUpdateTime metadata:type=\"Int64\">1580489088713</data:LastUpdateTime>\n" +
                                        "            <data:URI>http://localhost:8081/content.svc</data:URI>\n" +
                                        "            <data:ExtensionProperties metadata:type=\"#Collection(Tridion.WebDelivery.Platform.ContentKeyValuePair)\"></data:ExtensionProperties>\n" +
                                        "        </metadata:properties>\n" +
                                        "    </content>\n" +
                                        "</entry>", fromRequest().url().split('/')[-1].split('\'')[-2]))),
                        producer(file("response/defaultSomething.xml")))
        )
    }
}`
```

the problen is that `fromRequest().url()` doesn't seem to be working and when I try to insert

`print fromRequest().url()` 
in response section (in order to debug) I get as a result:

`
DslProperty{
clientValue={{{request.url}}},
        serverValue={{{request.url}}}}
`

instead of plain string `URL. .toString()` doesn't help neither. Do you have any ideas how can I get `request.url` as a plain string?

**Comment by marcingrzejszczak** [comment] 2020-04-01 10:06
Have you tried the latest version instead of RC2 ?

**Comment by ensigner** [comment] 2020-04-01 10:13
@marcingrzejszczak maybe I use wrong package, but I see that 2.2.0-RC2 is the latest one here https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-contract-verifier?repo=springio-plugins-release

**Comment by marcingrzejszczak** [comment] 2020-04-01 10:14
Why are you looking at springio-plugins-release instead of central? https://mvnrepository.com/artifact/org.springframework.cloud/spring-cloud-starter-contract-verifier

**Comment by ensigner** [comment] 2020-04-01 10:20
I am afraid that in my case it is determined on a level of project and I cannot change it myself (I am only governing a module). We will have to investigate if it's possible for us to migrate the whole project to further version. 
Meanwhile, locally, I can try with higher version of course by overriding this value

**Comment by ensigner** [comment] 2020-04-01 14:24
ok, in 2.2.2-RELEASE I get the same result, on

`print fromRequest().url()`

call I get returned: 
```
DslProperty{
clientValue={{{request.url}}},
        serverValue={{{request.url}}}}
```

instead of 
`/discovery.svc/something('defaultSomething')
`

line specified in contract to be used as url for producer

**Comment by OlgaMaciaszek** [comment] 2020-04-24 15:08
Hello, @ensigner . I'm not able to reproduce this issue. I have just retested it with the following contract:
 ```
Contract contractDsl = Contract.make {
	request {
	   method 'GET'
	   url("/discovery.svc/something(${value(consumer(regex(".*")), 
                                 producer('defaultSomething'))})" )
				}
	response {
	    status OK()
	    body(
	    url: fromRequest().url())
	}}
```
And this test was generated:

```
import static io.restassured.module.mockmvc.RestAssuredMockMvc.*;

@SuppressWarnings("rawtypes")
public class FooTest {

	@Test
	public void validate_() throws Exception {
		// given:
			MockMvcRequestSpecification request = given();


		// when:
			ResponseOptions response = given().spec(request)
					.get("/discovery.svc/something(defaultSomething)");

		// then:
			assertThat(response.statusCode()).isEqualTo(200);

		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).field("['url']").isEqualTo("/discovery.svc/something(defaultSomething)");
	}

}
```
in which the last line seems to be, in fact, what you were expecting to happen.

**Comment by spring-issuemaster** [comment] 2020-05-01 15:10
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2020-05-08 15:13
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-issuemaster** 2020-05-08 15:13 UTC
Labels: feedback-reminder, waiting for feedback
