### ISSUE TITLE
Stubs are created without considering the contextPath

### ISSUE THREAD

**Issue by lesongjia** [spring-cloud/spring-cloud-contract#117] opened 2016-10-20 19:21 UTC
I encounter an issue with stubs are not considering the contextPath. 

My case is I have a contextPath set in server. Then, I make a fatJar for client test. The client can not find the correct path due to the missing contextPath on stub runner.

For example, I have a contextPath set to server as "/server", then my endpoint for "/fraudcheck" in server will be "/server/fraudcheck". I will try to hit this endpoint in my client service, for instance something like "http://localhost:8080/server/fraudcheck".

I always get an error says no matching for "/server/fraudcheck" and the closet endpoint is "/fraudcheck".

**Comment by marcingrzejszczak** [comment] 2016-10-20 19:23
Btw how does this pass tests on producer side? It should already fail there or due to mock mvc it's passing properly?

**Comment by lesongjia** [comment] 2016-10-20 19:33
The producer tests are still passing. I assume it is b/c the fix in the other issue.

**Comment by lesongjia** [comment] 2016-10-20 19:45
[dsl-sample.zip](https://github.com/spring-cloud/spring-cloud-contract/files/542735/dsl-sample.zip)

This is the sample I used for testing. I can issue a PR or anything easy to find difference.

**Comment by marcingrzejszczak** [comment] 2016-10-22 08:12
This will be interesting... The stubs are created from the plugin, taking into consideration ONLY the contents of the contract. It has no knowledge of Context Path. I think we'd have to manually setup Spring Context to see the value of context path. I'll have to give it thought.

**Comment by lesongjia** [comment] 2016-10-23 23:44
Thanks @marcingrzejszczak 

I wonder whether there is a timeline for 1.0.2 release.

**Comment by marcingrzejszczak** [comment] 2016-10-24 06:50
We've just released `1.0.1` so it will take a while. Also I have to undust Sleuth a little bit and finish some stuff in Spring Cloud Pipelines...

**Comment by marcingrzejszczak** [comment] 2016-11-02 22:20
I had a chat with @snicoll and we've come to the conclusion that passing of context path will have to be done via a plugin configuration. There's no easy way to retrieve the context path at runtime.

**Comment by lesongjia** [comment] 2016-11-03 15:51
Thanks for your response. 

Do you have a timeline that when the plugin can be available? Or is that something we can implement by ourselves? 

We want to cover our contracts between microservices as soon as we can since we are a fast growing company. We tried PACT before but it does not go well.

**Comment by marcingrzejszczak** [comment] 2016-11-03 15:54
I'm working on some stuff related to Sleuth and I'd like to finish it. So I could (maybe) try to start doing it next week? Until now as a workaround you'd have to pass the full URL to the contracts. Is that an option for you?

**Comment by lesongjia** [comment] 2016-11-03 19:48
Thanks for the update.

Unfortunately, the workaround is not working since the dsl tests respect the contextPath, so if I pass the full URL to the contracts, my provider unit tests will fail. If not, the consumer integration tests will fail. 

We can definitely wait for this. Thanks!

**Comment by marcingrzejszczak** [comment] 2016-11-03 19:50
And what if you switch the mode `testMode` to `EXPLICIT` ? That way a real request should be sent to the real endpoint on the producer side. Can you please check it?

**Comment by lesongjia** [comment] 2016-11-04 15:46
I will try that and let you know. Thanks

**Comment by yacekmm** [comment] 2016-12-12 08:44
yeah, the context path on server side is an issue for me as well. my workaround is:
> url value(
                //solves ignoring context-path issue in cloud contract
                consumer("/contextPath/my-api"),
                producer("my-api"))

**Comment by marcingrzejszczak** [comment] 2016-12-28 11:54
@lesongjia have you tried it with the `EXPLICIT` mode ?

**Comment by marcingrzejszczak** [comment] 2016-12-28 18:59
As described in the docs:

The only thing that changes in order to fully support context paths is the switch on the PRODUCER side. The autogenerated tests need to be using the EXPLICIT mode.

The consumer side remains untouched, in order for the generated test to pass you have to switch the EXPLICIT mode.

```
<plugin>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-contract-maven-plugin</artifactId>
    <version>${spring-cloud-contract.version}</version>
    <extensions>true</extensions>
    <configuration>
        <testMode>EXPLICIT</testMode>
    </configuration>
</plugin>
```

That way you’ll generate a test that DOES NOT use MockMvc. It means that you’re generating real requests and you need to setup your generated test’s base class to work on a real socket.

Let’s imagine the following contract:

```
org.springframework.cloud.contract.spec.Contract.make {
	request {
		method 'GET'
		url '/my-context-path/url'
	}
	response {
		status 200
	}
}
```

Here is an example of how to set up a base class and Rest Assured for everything to work correctly.

```
import com.jayway.restassured.RestAssured;
import org.junit.Before;
import org.springframework.boot.context.embedded.LocalServerPort;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest(classes = ContextPathTestingBaseClass.class, webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
class ContextPathTestingBaseClass {

	@LocalServerPort int port;

	@Before
	public void setup() {
		RestAssured.baseURI = "http://localhost";
		RestAssured.port = this.port;
	}
}
```

That way all:

- all your requests in the autogenerated tests will be sent to the real endpoint with your context path included (e.g. /my-context-path/url)
- your contracts reflect that you have a context path, thus your generated stubs will also have that information (e.g. in the stubs you’ll see that you have too call /my-context-path/url)

Done via https://github.com/spring-cloud/spring-cloud-contract/commit/fb134a473d4f6085bfae58174b2e7e25549d49ff

**Closed by marcingrzejszczak** 2016-12-28 18:59 UTC
Labels: bug, in progress

**Comment by yacekmm** [comment] 2016-12-28 19:16
Oh... so this is the way to run tests on real context. I was searching for that. Is there any other way to setup explicit mode except maven file?

**Comment by marcingrzejszczak** [comment] 2016-12-28 19:20
Yeah - with Gradle you have the same https://github.com/spring-cloud/spring-cloud-contract/commit/fb134a473d4f6085bfae58174b2e7e25549d49ff#diff-941c557982bed7468185c4a1fc5c84f7R319 . But the problem is that... I broke EXPLICIT mode at some point ;) I've just fixed it too for this issue - https://github.com/spring-cloud/spring-cloud-contract/issues/179

**Comment by lesongjia** [comment] 2016-12-28 19:21
@marcingrzejszczak Thanks for the update. I haven't got a chance to try this yet. But from what you wrote, it makes sense.

**Comment by marcingrzejszczak** [comment] 2016-12-28 19:23
@lesongjia only now will it work cause previously you had no chance ;) Wait for 1.0.3 or 1.1.0 snapshots and only then try this out. I also checked your sample and I've managed to make it work but it would be nice to have it double checked :)

**Comment by lesongjia** [comment] 2016-12-28 19:25
@marcingrzejszczak Will try this definitely. We plan to come back to build our contracts in Q1. Thanks for the support!
