### ISSUE TITLE
Contract tests don't work with Kotlin 1.5

### ISSUE THREAD

**Issue by chrisbabsek** [spring-cloud/spring-cloud-contract#1662] opened 2021-05-17 10:18 UTC
**Describe the bug**
When upgrading the Kotlin version to version 1.5.0, our contract tests are not working anymore. When running them, it shows the following error message:
`Cannot invoke "String.hashCode()" because "this.email" is null
java.lang.NullPointerException: Cannot invoke "String.hashCode()" because "this.email" is  #null`

It seems that the project doesn't propagate the data from the requests to the controller. The problem doesn't occur with Kotlin version 1.4.31

**Comment by TYsewyn** [comment] 2021-05-17 10:34
Can you provide a [complete, minimal, verifiable sample](https://stackoverflow.com/help/mcve) that reproduces the problem? It should be available as a GitHub (or similar) project or attached to this issue as a zip file.
That way it will be a lot easier for us to troubleshoot the problem.

**Comment by spring-cloud-issues** [comment] 2021-05-24 10:37
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-cloud-issues** [comment] 2021-06-03 19:04
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spring-cloud-issues** 2021-06-03 19:04 UTC
Labels: feedback-reminder, waiting for feedback
