### ISSUE TITLE
spring-cloud-contract-maven-plugin causes maven to install/deploy 2 copies of maven-metadata.xml

### ISSUE THREAD

**Issue by ben-gineer** [spring-cloud/spring-cloud-contract#849] opened 2019-01-11 17:12 UTC
I have a problem using the spring-cloud-contract-maven-plugin. When we include the plugin in our maven project, maven then has a problem when running the maven-install or maven-deploy plugins, as can be seen here:

`mvn clean install -DskipTests -X`
```
[INFO] Installing /Users/bmiddleton/work/test/target/test-1.0-SNAPSHOT.jar to /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/test-1.0-SNAPSHOT.jar
[DEBUG] Writing tracking file /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/_remote.repositories
[INFO] Installing /Users/bmiddleton/work/test/pom.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/test-1.0-SNAPSHOT.pom
[DEBUG] Writing tracking file /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/_remote.repositories
[DEBUG] Installing com.mycompany:test:1.0-SNAPSHOT/maven-metadata.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/maven-metadata-local.xml
[DEBUG] Installing com.mycompany:test:1.0-SNAPSHOT/maven-metadata.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/maven-metadata-local.xml
[DEBUG] Installing com.mycompany:test/maven-metadata.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/maven-metadata-local.xml
[DEBUG] Installing com.mycompany:test/maven-metadata.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/maven-metadata-local.xml
[INFO] Installing /Users/bmiddleton/work/test/target/test-1.0-SNAPSHOT-stubs.jar to /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/test-1.0-SNAPSHOT-stubs.jar
[DEBUG] Writing tracking file /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/_remote.repositories
[DEBUG] Installing com.mycompany:test:1.0-SNAPSHOT/maven-metadata.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/maven-metadata-local.xml
[DEBUG] Installing com.mycompany:test:1.0-SNAPSHOT/maven-metadata.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/maven-metadata-local.xml
[DEBUG] Installing com.mycompany:test/maven-metadata.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/maven-metadata-local.xml
[DEBUG] Installing com.mycompany:test/maven-metadata.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/maven-metadata-local.xml
```

Similarly for deploy.

You'll see that maven installs/deploys 2 copies of the maven-metadata-local.xml (for install) or maven-metadata.xml (for deploy). This causes issues if the time between installing/deploying the first and second metadata file is more than a second on SNAPSHOT artifacts, where we end up with the metadata file with the wrong timestamp compared to the first metadata file. If I remove the spring-cloud-contract-maven-plugin then maven behaves correctly and only installs one copy of the maven-metadata file. For example:

`mvn clean install -DskipTests -X`

```
[INFO] Installing /Users/bmiddleton/work/test/target/test-1.0-SNAPSHOT.jar to /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/test-1.0-SNAPSHOT.jar
[DEBUG] Writing tracking file /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/_remote.repositories
[INFO] Installing /Users/bmiddleton/work/test/pom.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/test-1.0-SNAPSHOT.pom
[DEBUG] Writing tracking file /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/_remote.repositories
[DEBUG] Installing com.mycompany:test:1.0-SNAPSHOT/maven-metadata.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/1.0-SNAPSHOT/maven-metadata-local.xml
[DEBUG] Installing com.mycompany:test/maven-metadata.xml to /Users/bmiddleton/.m2/repository/com/mycompany/test/maven-metadata-local.xml
```

For a test case, you can create a project as follows:

pom.xml:
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>test</artifactId>
    <groupId>com.mycompany</groupId>
    <version>1.0-SNAPSHOT</version>
    <packaging>jar</packaging>

    <name>Test</name>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-starter-contract-verifier</artifactId>
                <version>2.0.2.RELEASE</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-contract-maven-plugin</artifactId>
                <version>2.0.2.RELEASE</version>
                <extensions>true</extensions>
                <configuration>
                    <baseClassForTests>com.mycompany.BaseClass</baseClassForTests>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
```

And I have a base test class as follows:
```
package com.mycompany;

public class BaseClass {
}
```

With a filesystem structure of:

```
.
└── src
    └── test
        ├── java
        │   └── com
        │       └── mycompany
        └── resources
            └── contracts
```

Also attached test.zip:

[test.zip](https://github.com/spring-cloud/spring-cloud-contract/files/2750508/test.zip)

I'm using maven 3.6.0, but this is also true on 3.5.2. I've also tried different versions of maven deploy and install (from 2.4 up to 3.0.0-M1), but have the same issue.

**Comment by marcingrzejszczak** [comment] 2019-01-11 19:01
Hmm interesting. Can you try without extensions section and provide the goals manually?

**Comment by ben-gineer** [comment] 2019-01-14 11:02
If I disable the extensions, I don't see this behaviour.

**Comment by LeatherOWL** [comment] 2019-01-18 12:24
But If I disable the extensions Contract tests are not been executed and stubs.jar not generated.

**Comment by marcingrzejszczak** [comment] 2019-01-18 12:39
You have to add the goals manually. Please read the docs

**Comment by LeatherOWL** [comment] 2019-01-18 14:46
Specifying <goal>generateTests</goal> manually and <extensions>false</extensions> cause same issue with double artifacts.

**Comment by OlgaMaciaszek** [comment] 2019-07-29 14:55
Does the problem still exist in the latest version?

**Comment by spring-issuemaster** [comment] 2019-08-05 14:59
If you would like us to look at this issue, please provide the requested information. If the information is not provided within the next 7 days this issue will be closed.

**Comment by spring-issuemaster** [comment] 2019-08-12 14:59
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Comment by LeatherOWL** [comment] 2019-08-16 12:35
Issue is still reproducible with 2.1.2.RELEASE version

**Comment by marcingrzejszczak** [comment] 2019-11-05 16:29
I've generated a fresh Spring Cloud Contract project from start.spring.io and with the latest Hoxton release, I see only one jar installation. With Greenwich however the problem persists. My suggestion, obviously, is to bump to Hoxton and if I have some spare time to fix this for Greenwich then I'll reopen the issue.

**Closed by marcingrzejszczak** 2019-11-05 16:29 UTC
Labels: bug

**Comment by ben-gineer** [comment] 2019-11-21 16:55
I still see this issue using the 2.1.3 version of the plugin. I'll try 2.1.4 once it's on maven central.

**Comment by marcingrzejszczak** [comment] 2019-11-21 17:19
Like i said, my suggestion is to bump to hoxton
