### ISSUE TITLE
@AutoConfigureWireMock(port = 0) complains about using 'fixed port'

### ISSUE THREAD

**Issue by kiesslingh** [spring-cloud/spring-cloud-contract#905] opened 2019-03-06 13:14 UTC
Bug Report
**Affects:** 2.1.0.RELEASE

When annotating a class with `@AutoConfigureWireMock(port = 0)`, WireMock allocates a random port. However, in the log we find the following confusing message from `org.springframework.cloud.contract.wiremock.WireMockTestExecutionListener`:
"You've used fixed ports for WireMock setup - will mark context as dirty. Please use random ports, as much as possible. Your tests will be faster and more reliable and thiswarning will go away".

This seems to be untrue on several accounts:
- A random port is used as expected, as is verifiable in the debugger
- Marking the context as dirty makes the tests way slower, as can be seen when using `@DirtiesContext` explicitly
- Nevertheless, the warning does not go away

**Comment by boothen** [comment] 2019-03-06 13:27
Sounds like the same issue as #883?

**Comment by kiesslingh** [comment] 2019-03-06 13:41
Actually, as I wrote, from all I can tell the annotation works as described and the context is _not_ marked as dirty. If I use the annotation `@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD`  explicitly, the single tests are way slower. Or is this like `@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_CLASS`?

**Comment by marcingrzejszczak** [comment] 2019-03-07 10:21
Yup, that seems like a duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/883

**Closed by marcingrzejszczak** 2019-03-07 10:21 UTC
Labels: waiting-for-triage
