### ISSUE TITLE
Maven-Plugin: convertToYaml fails on missing Request Headers

### ISSUE THREAD

**Issue by rroehrig** [spring-cloud/spring-cloud-contract#1875] opened 2023-03-06 17:04 UTC
**Describe the bug**
spring-cloud-contract-maven-plugin:4.0.1

We can generate stubs from groovy files to a stubs.jar with groovy files and mappings.
However when we set "convertToYaml" configuration option to the maven plugin, we get the following error:
```
Cannot invoke "org.springframework.cloud.contract.spec.internal.Headers.asMap(java.util.function.BiFunction)" because the return value of "org.springframework.cloud.contract.spec.internal.Request.getHeaders()" is null
```

We were able to identify that this issues occurs when "headers" is missing in the "request" of a contract.
However, according to the documentation (there are examples without headers), it should work without headers.

**Sample**
```
<plugin>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-contract-maven-plugin</artifactId>
  <extensions>true</extensions>
  <configuration>
    <testFramework>JUNIT5</testFramework>
    <testMode>MOCKMVC</testMode>
    <convertToYaml>true</convertToYaml>
    ...
  </configuration>
</plugin>
```
```
import org.springframework.cloud.contract.spec.Contract

Contract.make {
    request {
        method 'POST'
        url '/test'
        // headers is missing
    }
    response {
        status 201
    }
}

```
```
spring-cloud-contract:convert -f pom.xml
```

**Comment by arseniqueee** [comment] 2023-03-09 15:32
@rroehrig hi, i think i fix it https://github.com/spring-cloud/spring-cloud-contract/issues/1873, but it will be in 3.1.7 version

**Comment by marcingrzejszczak** [comment] 2023-03-09 15:34
Duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/1873

**Closed by marcingrzejszczak** 2023-03-09 15:34 UTC
Labels: duplicate
