### ISSUE TITLE
Aether downloads the cached version of the stub instead of the updated version from repositoryRoot

### ISSUE THREAD

**Issue by apansari** [spring-cloud/spring-cloud-contract#632] opened 2018-05-01 15:56 UTC
Use Case: If the producer DO NOT bump up the version or use `SNAPSHOT` to version the stub jar, make changes to the contract and push the contract stub jar to repositoryRoot keep version same.

Even after the stub artifact successfully updated in the repositoryRoot, however the consumer side using below coordinates, the latest stub jar changes does not reflect:

`@AutoConfigureStubRunner(repositoryRoot="http://artifactory.io.net/libs-release-local/", ids = {"com.example.contract:contract-example-service:**0.1.1**:stubs:8082"}, workOffline = false)
`
Note: using the fixed version in the version attribute.

Cloud contract version : `1.2.4.RELEASE`

**Comment by marcingrzejszczak** [comment] 2018-06-07 09:28
Do I remember that the problem is that if someone overrides the `0.1.1` version in Nexus / Artifactory, then whatever is cached locally will be picked? That's, of course, normal since non-snapshot versions are assumed to be immutable.

OTOH we should be ALWAYS picking values from a remote location. I guess we'll have to take a closer look on the Aether setup of JAR fetching.

**Comment by OlgaMaciaszek** [comment] 2018-09-03 15:00
Hello @apansari We think that fixing this issue might have resolved your problem as well: https://github.com/spring-cloud/spring-cloud-contract/issues/643 It was released in https://github.com/spring-cloud/spring-cloud-contract/milestone/38 . Please verify and get back to us to let us know if it's fixed.

**Comment by spencergibb** [comment] 2018-10-01 22:38
Closing due to lack of requested feedback. If you would like us to look at this issue, please provide the requested information and we will re-open the issue.

**Closed by spencergibb** 2018-10-01 22:38 UTC
Labels: enhancement, waiting for feedback
