### ISSUE TITLE
fromRequest().body() returns invalid JSON

### ISSUE THREAD

**Issue by BlainMaguire** [spring-cloud/spring-cloud-contract#459] opened 2017-11-15 14:34 UTC
Say you have a contract with response body:

```
"keywords" : fromRequest().body('$.meta.keywords')
```

And in a request to the wiremock server the client sends something like:

```
 { "meta": { "keywords" : ["keyword1", "keyword2"] }
```

I would expect that to just be echoed back to client but instead get invalid JSON. I.e. `"["keyword1", "keyword2"]"`

I haven't added meta.keywords to the request part of contract at all, so I decide to add something:

```
body("meta":["keywords" : [anyOf("keyword1","keyword2")]])
```

This _does_ return a valid JSON array of strings (and say "keyword3" if it was sent). (Now I'm sure there's a better way to say "keywords" is an array of non-empty strings but I digress).

Adding 'keywords' to the request part of the contract seems to fix the issue. Should it be required though? It seems to work fine without for simple strings, just when you're using anything else it's adding " to each side of the field, which can result in invalid JSON.

Anyway, as I added more fields to the request, I noticed something wrong with the response.

Say in my request part of the contract, meta gets a bit more complicated, like it has three layers of nesting in the request body of the contract, like:

```
"meta": [
                        "a"            : "A",
                        "b"               : [
                                "c"      : [
                                        "A",
                                        "B"
                                ],
                                "d"       : "C"
                        ]
                ]
```

Here I've just used static values in the request here, so it's easier to follow. Then I send some JSON body on which matches it. In this case making sure I have this in it: 

`"meta" : {"a" : "A", "b" : {"c" : ["A", "B"], "d": "C"}}}}`

In the response body of the request, wiremock matches but I see invalid JSON being returned for this, namely things like:

`{a=A, b={c=["A","B"], d=C}}`

Which is strange. Again, I use fromRequest() to return the object to the client. Specifically fromRequest().body('$.meta') in this test example.

I tried this on the latest 1.2.0.BUILD-SNAPSHOT today. All requests are with: method 'POST', I haven't added any stubMatchers for the meta field, as I'm using other fields to match. And the url is just hardcoded.

Happy to send on any more information you need.

Best Regards,
Blain

**Comment by marcingrzejszczak** [comment] 2017-11-15 14:40
> Adding 'keywords' to the request part of the contract seems to fix the issue. Should it be required though? It seems to work fine without for simple strings, just when you're using anything else it's adding " to each side of the field, which can result in invalid JSON.

I don't understand this part at all. Can you elaborate on what the problem is?

Can you paste the full contract and the generated WireMock stubs?

As I understand the tests are generated correctly but the stubs don't work as they should?

**Comment by BlainMaguire** [comment] 2017-11-15 14:56
Tests are generated without any issue, it's just when I'm testing it myself through wiremock I noticed the problem.

Something like:
```
request {
  body("a" : "1")
}
response {
  body("meta" : fromRequest().body("$.meta")
}
```
Works fine, if the client sends "meta" : "mystring", but deciding to send: "mystring" : 42, results in "42", and likewise ["1", "2"] becomes "["1", "2"]" for some reason.

Then adding in "meta" into request{ } seems to get around that, but should it be required?

Lastly, I noticed some weirdness when I started to make it a more complicated object, _even if_ I include it in the request part of  the contract.

I hope this is clearer.

**Comment by marcingrzejszczak** [comment] 2017-11-15 14:58
What you wrote makes no sense. There's no `$.meta` in the request. Response requires `meta` to be there but you don't set it in the request. I don't think that it's related to Contract at all. 

I asked you to paste the wiremock stubs. Could you please do it?

**Comment by marcingrzejszczak** [comment] 2017-11-15 14:58
Also can you paste the generated tests?

**Comment by BlainMaguire** [comment] 2017-11-15 15:20
Full contract:

```
org.springframework.cloud.contract.spec.Contract.make {
    request {
        method 'POST'
        url '/api/payment/v1/payments'
        headers {
            header 'Content-Type', 'application/json'
        }
        body('data': ['test': 1
        ],
                "meta": [
                        "a"            : "A",
                        "b"               : [
                                "c"      : [
                                        "A",
                                        "B"
                                ],
                                "d"       : "C"
                        ]
                ])
    }
    response {
        status 201
        headers {
            header(
                    'Content-Type', value(consumer('application/json'), producer(regex('application/json.*')))
            )
        }
        body("Data": [
                "status"          : "Pending",

                "test"      :       fromRequest().body('$.data.test'),
                "info"            : fromRequest().body('$.meta'),
                "links"           : ["self": fromRequest().path()],
        ]
        )

    }
    priority 1
}
```

Wiremock JSON:

```
{
  "id" : "9608c170-de32-4253-a084-1d6e3513972b",
  "request" : {
    "url" : "/api/payment/v1/payments",
    "method" : "POST",
    "headers" : {
      "Content-Type" : {
        "equalTo" : "application/json"
      }
    },
    "bodyPatterns" : [ {
      "matchesJsonPath" : "$.['data'][?(@.['test'] == 1)]"
    }, {
      "matchesJsonPath" : "$.['meta'][?(@.['a'] == 'A')]"
    }, {
      "matchesJsonPath" : "$.['meta'].['b'].['c'][?(@ == 'B')]"
    }, {
      "matchesJsonPath" : "$.['meta'].['b'].['c'][?(@ == 'A')]"
    }, {
      "matchesJsonPath" : "$.['meta'].['b'][?(@.['d'] == 'C')]"
    } ]
  },
  "response" : {
    "status" : 201,
    "body" : "{\"Data\":{\"test\":{{{jsonpath this '$.data.test'}}} ,\"links\":{\"self\":\"{{{request.path}}}\"},\"status\":\"Pending\",\"info\":{{{jsonpath this '$.meta'}}} }}",
    "headers" : {
      "Content-Type" : "application/json"
    },
    "transformers" : [ "response-template" ]
  },
  "uuid" : "9608c170-de32-4253-a084-1d6e3513972b",
  "priority" : 1
}
```

And generated tests:

```
package ie.aib.msf.apigee.contracts;

import com.jayway.jsonpath.DocumentContext;
import com.jayway.jsonpath.JsonPath;
import ie.aib.msf.apigee.contracts.Payment_initiation_clientBase;
import io.restassured.module.mockmvc.specification.MockMvcRequestSpecification;
import io.restassured.response.ResponseOptions;
import org.junit.Test;

import static com.toomuchcoding.jsonassert.JsonAssertion.assertThatJson;
import static io.restassured.module.mockmvc.RestAssuredMockMvc.*;
import static org.springframework.cloud.contract.verifier.assertion.SpringCloudContractAssertions.assertThat;

public class Payment_initiation_clientTest extends Payment_initiation_clientBase {

	@Test
	public void validate_post-payments-initation-success() throws Exception {
		// given:
			MockMvcRequestSpecification request = given()
					.header("Content-Type", "application/json")
					.body("{\"data\":{\"test\":1},\"meta\":{\"a\":\"A\",\"b\":{\"c\":[\"A\",\"B\"],\"d\":\"C\"}}}");

		// when:
			ResponseOptions response = given().spec(request)
					.post("/api/payment/v1/payments");

		// then:
			assertThat(response.statusCode()).isEqualTo(201);
			assertThat(response.header("Content-Type")).matches("application/json.*");
		// and:
			DocumentContext parsedJson = JsonPath.parse(response.getBody().asString());
			assertThatJson(parsedJson).field("['Data']").field("['links']").field("['self']").isEqualTo("/api/payment/v1/payments");
			assertThatJson(parsedJson).field("['Data']").field("['status']").isEqualTo("Pending");
			assertThatJson(parsedJson).field("['Data']").field("['info']").isEqualTo({a=A, b={c=["A","B"], d=C}});
			assertThatJson(parsedJson).field("['Data']").field("['test']").isEqualTo(1);
	}

}
```


Curl command:

`curl -X POST  http://localhost:8083/api/payment/v1/payments -d '{"data": {'test' : 1},"meta":{"a" : "A", "b" : {"c" : ["A", "B"], "d": "C"}}}}' -H "Content-Type: application/json"`

Result:

Response:
HTTP/1.1 201
Content-Type: [application/json]

`{"Data":{"test":1 ,"links":{"self":"/api/payment/v1/payments"},"status":"Pending","info":{a=A, b={c=["A","B"], d=C}} }}`

**Comment by marcingrzejszczak** [comment] 2017-11-15 15:24
I think this is a duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/363 . Can you confirm it?

**Comment by BlainMaguire** [comment] 2017-11-15 16:46
So yeah, I can confirm for really simple values for meta, like 1, [1] and ["1"], they seem to be fine at least. It's only when I start to add objects into what I send that I get those '=' in the wiremock response. So it looks like a duplicate.

For checking for the existence of such objects (like meta) in the request, what's the best way to do that in the contract? My leaving it out entirely made sense initially since the server wasn't echoing it back. Thanks!

**Comment by marcingrzejszczak** [comment] 2017-11-22 13:12
Closing this in favour of https://github.com/spring-cloud/spring-cloud-contract/issues/363

**Closed by marcingrzejszczak** 2017-11-22 13:12 UTC
Labels: waiting for feedback
