### ISSUE TITLE
Regression with generating multipart requests

### ISSUE THREAD

**Issue by aplotnikov** [spring-cloud/spring-cloud-contract#1667] opened 2021-06-01 10:36 UTC
After migration from Spring Cloud contract 2.2.7.RELEASE to 3.0.3. Cloud contract tests which use multipart content-type started failing with 400 Bad Request reason. After the analyse of the generated contracts I have found that one line is missed into the new version of Spring Cloud contracts.

Example of the contract - contract wasn't changed between the versions
```
Contract.make {
    request {
        method POST()
        url '/attachments'
        headers {
            header 'Content-Type': value(client(regex('multipart/form-data; ?boundary=.+')), server('multipart/form-data;boundary=AaB03x'))
        }
        multipart(
            file: named(
                name: $(c(regex(nonEmpty())), p('filename.csv')),
                content: $(c(regex(nonEmpty())), p('file content'))
            )
        )
    }
    response {
        status CREATED()
    }
}
```

It is almost the same as example provided here - https://cloud.spring.io/spring-cloud-contract/reference/html/project-features.html#contract-dsl-multiple

The generated code in Spring Cloud contract version 2.2.7.RELEASE
```
def validate_shouldReturnCreatedForUploadAttachments() throws Exception {
   given:
      RequestSpecification request = given()
            .header("Content-Type", "multipart/form-data;boundary=AaB03x")
            .multiPart('file', 'filename.csv', 'file content'.bytes)
   when:
      Response response = given().spec(request)
            .post("/attachments")
   then:
      response.statusCode() == 201
}
```

The generated code in  Spring Cloud contract version 3.0.3

```
	def validate_shouldReturnCreatedForUploadAttachments() throws Exception {
		given:
			RequestSpecification request = given()
					.header("Content-Type", "multipart/form-data;boundary=AaB03x")

		when:
			Response response = given().spec(request)
					.post("/attachments")

		then:
			response.statusCode() == 201
	}
```

It is possible to spot that the following line is missed
```.multiPart('file', 'filename.csv', 'file content'.bytes)```

When I have added this line manual and run the test with the new version of Spring Cloud contracts it passed however I am not able to force proper generation of the contract with this line.

**Comment by igarash1** [comment] 2022-03-21 00:30
Hi, I tried to reproduce this bug, but couldn't reproduce it. Generated codes in both versions 2.2.7.RELEASE and 3.0.3 seem to contain `.multiPart('file', 'filename.csv', 'file content'.bytes)` correctly. Maybe need the steps to reproduce it.

**Comment by aplotnikov** [comment] 2022-03-21 08:33
I provided the example of the specification. What extra steps can I provide you?

I have re-written those tests to average integration tests so I can not check in my source code anymore. Which was a good idea as since I reported the issue passed almost 9 months.

**Comment by aplotnikov** [comment] 2022-03-21 08:41
What I know for sure compare to your use cases you test usually in maven but my code is in Gradle. In that moment it was version 6.x but which exactly version I don't remember.

**Comment by marcingrzejszczak** [comment] 2022-03-21 08:43
> I provided the example of the specification. What extra steps can I provide you?

Preferably a sample that reproduces the problem. 

BTW as you can see this issue is marked as `good first issue` or `gracehopperOSD` so there are people who are interested in getting into open source and helping us out. That means that we should do our best to be as kind as possible to them (in general we should be doing this but here we should do even more ;) ).

**Comment by aplotnikov** [comment] 2022-03-21 08:56
Could you be more specific about what is required?

I tried to do my best. I think I prepared the sample. `Provide steps to reproduce` is not so specific question as step to reproduce is to run tests e.g. `gw clean build`

I am OK to help that's why I created this ticket.

Environment: Gradle 6.x, Groovy 2.5.x (I suppose 12). I suppose tests were run via JUnit 5 platform (but now I am not sure it was pretty far away).

**Comment by marcingrzejszczak** [comment] 2022-03-21 09:00
Please push some code that is failing to a repo on github that reproduces the problem. That way we will be sure that we can easily replicate the issue.

**Comment by igarash1** [comment] 2022-03-21 13:27
I tried it again in the environment @aplotnikov provided, but still cannot reproduce it. Here is the repo I used for checking: https://github.com/igarash1/spring-cloud-contract-issue1667

**Comment by aplotnikov** [comment] 2022-03-21 13:33
His is the repo. You can find the generated test but the process itself doesn't work.
You can run clean build and generate test.

https://github.com/aplotnikov/cloud-contract-test

**Comment by aplotnikov** [comment] 2022-03-21 13:34
I have tried to create is ASAP so something can be cleaned up or so.

**Comment by aplotnikov** [comment] 2022-03-21 13:37
I have found a pattern already sounds like when `testMode = 'Explicit'` is removed it works properly.

**Comment by aplotnikov** [comment] 2022-03-21 13:40
With explicit

```
package com.example.cloudcontracttest

import com.example.cloudcontracttest.BaseContractSpec
import spock.lang.Specification
import io.restassured.module.mockmvc.specification.MockMvcRequestSpecification
import io.restassured.response.ResponseOptions

import static org.springframework.cloud.contract.verifier.assertion.SpringCloudContractAssertions.assertThat
import static org.springframework.cloud.contract.verifier.util.ContractVerifierUtil.*
import static io.restassured.module.mockmvc.RestAssuredMockMvc.*

@SuppressWarnings("rawtypes")
class ContractVerifierSpec extends BaseContractSpec {

	def validate_shouldTest() throws Exception {
		given:
			MockMvcRequestSpecification request = given()
					.header("Content-Type", "multipart/form-data;boundary=AaB03x")
					.multiPart('file', 'filename.csv', 'file content'.bytes)


		when:
			ResponseOptions response = given().spec(request)
					.post("/attachments")

		then:
			response.statusCode() == 201
	}

}

```

Without explicit
```
package com.example.cloudcontracttest

import com.example.cloudcontracttest.BaseContractSpec
import spock.lang.Specification
import io.restassured.specification.RequestSpecification
import io.restassured.response.Response

import static org.springframework.cloud.contract.verifier.assertion.SpringCloudContractAssertions.assertThat
import static org.springframework.cloud.contract.verifier.util.ContractVerifierUtil.*
import static io.restassured.RestAssured.*

@SuppressWarnings("rawtypes")
class ContractVerifierSpec extends BaseContractSpec {

	def validate_shouldTest() throws Exception {
		given:
			RequestSpecification request = given()
					.header("Content-Type", "multipart/form-data;boundary=AaB03x")

		when:
			Response response = given().spec(request)
					.post("/attachments")

		then:
			response.statusCode() == 201
	}

}

```

**Comment by aplotnikov** [comment] 2022-03-21 13:40
Path where the test is located `build/generated-test-sources/contractTest/groovy/com/example/cloudcontracttest`

**Comment by marcingrzejszczak** [comment] 2022-03-21 13:44
So actually it works for `EXPLICIT` and doesn't for `MOCKMVC` ?

**Comment by aplotnikov** [comment] 2022-03-21 13:50
I don't know what you mean by works fine.
I think the issue is reproducible for `EXPLICIT` but for `MOCKMVC` works fine = no issues.

**Comment by aplotnikov** [comment] 2022-03-21 13:52
I made a mistake in my first message https://github.com/spring-cloud/spring-cloud-contract/issues/1667#issuecomment-1073910521

I correct it in this message https://github.com/spring-cloud/spring-cloud-contract/issues/1667#issuecomment-1073921643

**Comment by marcingrzejszczak** [comment] 2022-03-21 14:15
Most likely we're missing sth around here https://github.com/spring-cloud/spring-cloud-contract/blob/e73d6526bfb3240f9dc33d6afcf2be17e5383f49/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/RestAssuredGiven.java#L46 . That means that for EXPLICIT we're NOT generating a line for `multipart` but we're generating one for `MOCKMVC`

**Comment by igarash1** [comment] 2022-03-22 09:11
I was able to reproduce it in 3.1.1, and I also found that even for `WEBTESTCLIENT` (=testMode) it's not generating `multipart` as well.
I think we can add a class(sth like `SpockExplicitMultipartGiven`) [here](https://github.com/spring-cloud/spring-cloud-contract/blob/6e951e60fdda57f5e7eec22178415a282390aa4c/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/RestAssuredGiven.java#L45-L46) to fix this case, but can we just combine  [JavaMultipartGiven](https://github.com/spring-cloud/spring-cloud-contract/blob/9949ebe4a98c419db5493d6385f1d6917230dd6a/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/JavaMultipartGiven.java#L29) and  [SpockMockMvcMultipartGiven](https://github.com/spring-cloud/spring-cloud-contract/blob/9949ebe4a98c419db5493d6385f1d6917230dd6a/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/SpockMockMvcMultipartGiven.java#L28) into a single class? because it seems they do the same thing.

**Comment by marcingrzejszczak** [comment] 2022-03-22 09:48
They differ by this line https://github.com/spring-cloud/spring-cloud-contract/blob/9949ebe4a98c419db5493d6385f1d6917230dd6a/spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/builder/SpockMockMvcMultipartGiven.java#L68 . Yeah something is wrong with multipart in general. Indeed we should add some code where you mentioned for `webTestClient` approach and `explicit`. The idea of the architecture that we created there is to prefer duplication but have clear separation between those configuration options (webtestclient, explicit, spock etc.), so let' leave those separated but let's add the missing implementations

**Comment by igarash1** [comment] 2022-03-22 10:09
I see. It makes sense. I will try to make PR for this. Thanks for helping me @aplotnikov @marcingrzejszczak

**Closed** 2022-06-20 15:00 UTC
Labels: bug, feedback-provided, good first issue, status: reserved-for-conference-event
