### ISSUE TITLE
Gradle 7 support

### ISSUE THREAD

**Issue by ArjanSchouten** [spring-cloud/spring-cloud-contract#1643] opened 2021-04-21 08:57 UTC
**Describe the bug**
When running `./gradlew clean build` with gradle 7 the build fails.

* What went wrong:
```
A problem was found with the configuration of task ':copyContracts' (type 'ContractsCopyTask').
  - Type 'ContractsCopyTask.Dependency' method 'toStubConfiguration()' should not be annotated with: @Internal.

    Reason: Input/Output annotations are ignored if they are placed on something else than a getter.

    Possible solutions:
      1. Remove the annotations.
      2. Rename the method.

    Please refer to https://docs.gradle.org/7.0/userguide/validation_problems.html#ignored_annotations_on_method for more details about this problem.
```

With gradle 6.8.3 we had deprecation warnings already: 
```
Type 'ContractsCopyTask.Dependency': non-property method 'toStubConfiguration()' should not be annotated with: @Internal. This behaviour has been deprecated and is scheduled to be removed in Gradle 7.0. See https://docs.gradle.org/6.8.3/userguide/more_about_tasks.html#sec:up_to_date_checks for more details.
```

**Comment by marcingrzejszczak** [comment] 2021-04-21 08:58
Duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/1636

**Closed by marcingrzejszczak** 2021-04-21 08:58 UTC
Labels: waiting-for-triage

**Comment by ArjanSchouten** [comment] 2021-04-21 08:59
Ah thanks. Couldn't find it. Searched for open issues only 🤦
