### ISSUE TITLE
Cannot make contract to root of server with JSON body checking

### ISSUE THREAD

**Issue by PROrock** [spring-cloud/spring-cloud-contract#535] opened 2018-01-29 15:54 UTC
I cannot seem to build a contract to root path (/).
This happens only if there is JSON body checking.

Sample:
```
import org.springframework.cloud.contract.spec.Contract

Contract.make {
    request {
        description "Root request"
        method 'GET'
        urlPath '/'
    }
    response {
        status 200
        body(
                [
                    _doc: $(c("platformId"), p(regex(nonEmpty()))),
                ]
        )
    }
}
```

Maven build log:
`[ERROR] Failed to execute goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.2.0.BUILD-SNAPSHOT:generateTests (default-generateTests) on project api-producer: Execution default-generateTests of goal org.springframework.cloud:spring-cloud-contract-maven-plugin:1.2.0.BUILD-SNAPSHOT:generateTests failed: Index: 0, Size: 0 -> [Help 1]`

I have traced it to class and method `org.springframework.cloud.contract.verifier.builder.TestSideRequestTemplateModel#buildPathsFromUrl`
in line: 
`paths.remove(0)`

I have also figured out a workaround:
`urlPath $(c('/'), p(execute('"/"')))`

My spring-cloud.version is Edgware.RELEASE

**Comment by marcingrzejszczak** [comment] 2018-01-29 15:55
Duplicate of https://github.com/spring-cloud/spring-cloud-contract/issues/465. Please use `Edgware.SR1`

**Closed by marcingrzejszczak** 2018-01-29 15:55 UTC
