### ISSUE TITLE
UnknownHostException on ec2

### ISSUE THREAD

**Issue by nekperu15739** [spring-cloud/spring-cloud-contract#1386] opened 2020-04-24 14:16 UTC
**Describe the bug**
Im developing an application which works perfect in local, however, when try to test on jenkins(ec2) is throwing an `java.net.UnknownHostException: ip-XX-XXX-XX-XXX.` 

Follow the stacktrace looks like a problem related with wiremock dependency that use ip. 

> HostnameHelper.java:31

`HOSTNAME = InetAddress.getLocalHost().getHostName();`

However, is wondering **why is really ip needed? since i set config to work local**. Is only for  produce contracts. And even further in other project i get the ip, however, not throw erros and hosts file looks simitar.

/etc/hosts

`+ cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost6 localhost6.localdomain6`

Those are my dependencies:
`<dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>spring-web-test-client</artifactId>
            <scope>test</scope>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-contract-verifier</artifactId>
            <scope>test</scope>
        </dependency>`

this is plugin config:

`<plugin>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-contract-maven-plugin</artifactId>
                <version>${spring-cloud-contract.version}</version>
                <extensions>true</extensions>
                <configuration>
                    <testFramework>JUNIT5</testFramework>
                    <testMode>WEBTESTCLIENT</testMode>
                    <packageWithBaseClasses>proxy.api</packageWithBaseClasses>
                    <contractsMode>LOCAL</contractsMode>
                </configuration>
            </plugin>`

those are versions:
`<spring-cloud.version>Hoxton.SR3</spring-cloud.version>
        <rest-assured.version>4.0.0</rest-assured.version>
        <spring-cloud-contract.version>2.2.2.RELEASE</spring-cloud-contract.version>`

i public problem on [here](https://stackoverflow.com/questions/61398742/spring-cloud-contract-unknownhostexception) .

**Comment by OlgaMaciaszek** [comment] 2020-04-24 14:35
Please provide a [minimal, complete, verifiable example](https://stackoverflow.com/help/mcve) that reproduces the issue. Please indicate exactly which build goals you are running. 
Btw., why are you using `LOCAL` mode in your Jenkins? The local mode is for working on implementing the API which should usually be a complete step when the code reaches Jenkins build (i.e. the changes have been merged).

**Comment by nekperu15739** [comment] 2020-04-24 14:46
Hi, in running: `/opt/mvn/bin/mvn -X clean install` 
about example, could you share me and email, bc, is private repository.

**Comment by OlgaMaciaszek** [comment] 2020-04-24 15:14
@nekperu15739 just make a sample project that reproduces the same issue - remove all the things not necessary to understand your SC Contract setup, including your private business bits - i.e. if you have endpoints with business logic, remove them and add a simplest possible endpoint (returning a String or sth) - we just want to see your plugin setup, config and contracts.

Also, please indicate why you're using the `local` mode in Jenkins.

**Comment by nekperu15739** [comment] 2020-04-25 13:16
Hi, 

I add project [here](https://github.com/nekperu15739/contract-sample)

before run, execute this script:

`/etechlog-be-proxy-parent/etechlog-be-proxy-api/src/test/resources/infrastructure.sh`

kind regargs

**Comment by nekperu15739** [comment] 2020-04-30 13:59
@OlgaMaciaszek i will do the changes as soon as possible.

**Comment by nekperu15739** [comment] 2020-05-10 14:38
Hi, 

Changes are done.

**Comment by marcingrzejszczak** [comment] 2020-05-20 07:56
If the issue is in `HostnameHelper` then you should ping WireMock folks about this. We can't do much about this I guess.

**Comment by nekperu15739** [comment] 2020-05-20 22:41
> If the issue is in `HostnameHelper` then you should ping WireMock folks about this. We can't do much about this I guess.

Certainly is true what do you mention, however, knowing this use case i believe is posible catch the exception and look for other strategy or directly not ask for ip if is not need. To me is not really clare why ip is needed.

**Comment by marcingrzejszczak** [comment] 2020-05-21 07:30
You can register your own extensions and do it yourself as a workaround (please check https://cloud.spring.io/spring-cloud-static/spring-cloud-contract/2.2.2.RELEASE/reference/htmlsingle/#customization-wiremock-extension). We'd prefer not to leave such workarounds in the code.

**Closed by marcingrzejszczak** 2020-05-21 07:30 UTC
Labels: feedback-provided
