### ISSUE TITLE
InputDestination and OutputDestination for test using @Import(TestChannelBinderConfiguration.class) have binding Autowired as per 'destination' name and not what the destination is for in the Config File

### ISSUE THREAD

**Issue by prasadchavan231989** [spring-cloud/spring-cloud-contract#1673] opened 2021-06-15 14:56 UTC
I upgraded my app:

Spring boot 2.3.3.RELEASE -> 2.4.6
Spring cloud Hoxton.SR8 -> 2020.0.3

After this upgrade and using new dependency like spring-cloud-stream -- test binder, to get the contract test working in annotation based cloud stream approach. 
My integration tests starting failing ( MessageCollector class not found). To resolve this issue used TestChannelBinderConfiguration along with InputDestination and OutputDestination to send and receive messages. but facing below issue:

Have a test config class : 
```
@Configuration
@Import(TestChannelBinderConfiguration.class)
public class RabbitTestConfig {
//extra bean for configuration
}
```
Application.yml ::
```
spring:
  cloud:
    stream:
      bindings:
        cloud-channel-request:
          destination: request-topic
      cloud-channel-request:
          destination: response-topic

      <many more binding likes this>

```

Spring boot test class for testing flow from 'cloud-channel-request'  to 'cloud-channel-request'

```
@SpringBootTest
@DisplayName("IntegrationTest ")
public class EventIntegrationTest {

 @Autowired
 private InputDestination inputDestination;
 @Autowired
 private OutputDestination outputDestination;

<followed by the test code...>
}
```

The problem here is if you debug InputDestination and OutputDestination they both have beans registered by the name which are present in the destination part of the config like 'request-topic' and not 'cloud-channel-request' which should have been the case.

Since it is not, wouldn't it defeat the purpose of loose coupling with any messagerbroker like rabbitMQ for example.
As now we would have to send and receive messages by giving values like 'request-topic' and 'response-topic' respectively.
example :  `inputDestination.send(MessageBuilder.withPayload(request).build(), "request-topic");`
 

Please help me understand if this is an issue or I am missing something here .
**NOTE**: These Inegration tests worked fine before, with use of MessageCollector along with InputChannel and Outputchannel

**Comment by olegz** [comment] 2021-06-15 15:25
Yes, you are missing an important point. 

Spring Cloud Stream as a framework was designed to connect broker destinations to a piece of code provided by a user. That connection mechanism is called _binding_ and it is exposed to the end user to allow them to provide additional configurations. Discussing these configuration is out of scope of this response, other than to say that outside of such configurations there should not be direct interaction between the binding  and the end user. ***_Messages are always sent to a broker destination and received from a broker destination. Binders (e.g., Kafka, Rabbit) connect these destinations to a code (functions) provided by the user effectively triggering its invocation_***

When user does not specify binding destination property (like you did), then _binding name_ and _destination name_ is the same and you can see those destinations being generated/provisioned by the binders. 

Now to the Test Binder. . .

Test Binder is no different than any other binder as it connects the broker destinations to your code. However, the role of the broker is effectively played by [Spring Integration](https://spring.io/projects/spring-integration) framework. In the scope of this question you can think of it as an embedded messaging system. We use it to emulate the same interaction you would have with systems like Rabbit, Kafka etc., to make sure that our local testing validates the same mechanisms used by other binders So when dealing with test binder you are (as with other binders) _sending to_ and _receiving from_ broker destinations. . . ALWAYS!

**Closed by olegz** 2021-06-15 15:25 UTC
Labels: question

**Comment by prasadchavan231989** [comment] 2021-06-15 16:45
Hi Oleg, 
Thank you for prompt response .
But As I have given in the config example  'cloud-channel-request' is the binding name and 'request-topic' is the destination name if I am not wrong.?

**Comment by olegz** [comment] 2021-06-15 17:03
The `cloud-channel-request` is a binding name for destination  `request-topic` and so on

**Comment by olegz** [comment] 2021-06-15 17:07
Also, I made a bit of a mistake in my explanation which may have confused you. When i said _When user does not specify binding destination property (like you did), then binding name..._, the `(like you did)` is wrong in the context of that sentence since you actually DID provide explicit mapping between the binding and destination.
If you didn't define the `destination` property at all you would end up with binding name `cloud-channel-request` and destination with the same name `cloud-channel-request`

**Comment by prasadchavan231989** [comment] 2021-06-15 17:16
I am afraid I may have not explained my concern here correctly. So as per our above conversation since the binding name and destinations are setup correctly . 
I wanted to know why do I have to do something thing like this ---
`inputDestination.send(MessageBuilder.withPayload(request).build(), "request-topic");` -- where 'request-topic' is the destination name.

As below throws exception(null pointer) since it doesn't find any bean autowired 
`inputDestination.send(MessageBuilder.withPayload(request).build(), "cloud-channel-request");` -- binding name 


isn't using the destination name(request-topic) kind of coupling it with the message broker used?

**Comment by olegz** [comment] 2021-06-16 08:02
As I stated before, The Test Binder emulates a relationship of a binder with the message broker. To ensure this emulation we enforce interaction directly with destination as if you would while using Rabbit, Kafka or any other message broker.
